### ISSUE TITLE
feat: Support retrieving domain expiration date via WHOIS

### ISSUE THREAD

**Issue by evsyukovaa** [TwiN/gatus#133]
Is it possible to track dns, dns expiration date as for certificates.
`whois google.ru`
`created: 2004-03-03T21: 00: 00Z`
`paid-till: 2022-03-04T21: 00: 00Z`
`free-date: 2022-04-05`
DNS does not have such a function, or I don’t know how to do it?

**Comment by TwinProduction** [comment]
By "dns expiration date", you meant the domain expiration date, right?

That data is actually exposed by the registrars AFAIK, not the DNS, and WHOIS is the "protocol" used to access the information.
It's not currently supported, but I can see that being a useful feature.

**Comment by evsyukovaa** [comment]
yes, it will be enough to know when "paid till" and show it if the due date approaches.
Need to create a task about this)?

**Comment by TwiN** [comment]
I lazily implemented WHOIS in https://github.com/TwiN/whois and I'm thinking about implementing monitoring for TLD expiration.

Should be as simple as using `strings.Index` with the knowledge that `Registry Expiry Date:` and `\n` are the two strings wrapping the data we're interested in.

That being said, https://github.com/TwiN/whois might need some more polishing
