### ISSUE TITLE
Data retention

### ISSUE THREAD

**Issue by xoraingroup** [TwiN/gatus#137]
Is there any switch or configuration to configure gatus for data retention when storing data in file?  

Like data_retention: 30d / 4d etc

**Comment by TwinProduction** [comment]
Hello @xoraingroup, that setting doesn't currently exists, but since v2.1.0, I have started making modifications to support a longer result history, and considering the database storage implementation I'm currently working on, it shouldn't be long before this feature will be added.

**Comment by xoraingroup** [comment]
Awesome as always. Thank you :)

**Comment by TwiN** [comment]
Duplicate of #128
