### ISSUE TITLE
Installing gatus in a linux server outside docker o k8s

### ISSUE THREAD

**Issue by codesse** [TwiN/gatus#163]
Hello,
maybe it's not the focus of the project, but is there a (documented) way to install gatus a a service (systemd, or whatever) instead of inside a k8s cluster or docker?
Thanks!

**Comment by codesse** [comment]
Thanks Chris,

I'll give it a try.

Regards,

**Comment by karljohns0n** [comment]
Hello,

I'm currently using docker golang image to build Gatus and I run it using systemd. It works very well.
