### ISSUE TITLE
Telegram notification for supergroup upgraded chat

### ISSUE THREAD

**Issue by niondir** [TwiN/gatus#179]
I got the following message for my send message request. Switching to the `migrate_to_chat_id` works. The bot could do this implicitly. I'm not sure why the upgrade happend. But it would be nice if it does not affect the telegram bot.

Response from sendMessage:
```
{ 
    "ok": false, 
    "error_code": 400, 
    "description": "Bad Request: group chat was upgraded to a supergroup chat", 
    "parameters": { 
        "migrate_to_chat_id": -1001557912345 
    } 
}
```

Expected behavior:
Switch to `migrate_to_chat_id`

**Comment by jon4hz** [comment]
Telegram automatically upgrades groups to supergroups when they reach a certain amount of members or if you set "Chat history for new members" to visible. If a group gets upgraded, it gets a new group id, in your case -1001557912345. Normally groups aren't upgraded just out of the blue so imo it's not up to the bot to handle that but up to the user to set the correct chat id.

**Comment by TwiN** [comment]
@jon4hz Thank you for clarifying - I didn't have the necessary Telegram knowledge to help with this.

With that in mind, I'm going to close this issue.
