### ISSUE TITLE
feat: mTLS configuration for HTTPS and TCP monitors

### ISSUE THREAD

**Issue by cruscio** [TwiN/gatus#189]
Please add the ability to specify client certificate & key, and server CA certificate, for monitoring of HTTPS & TLS endpoints that require mTLS handshakes (and/or use self-signed server certificates). For example: monitoring [Kafka Broker](https://docs.confluent.io/platform/current/kafka/configure-mds/mutual-tls-auth-rbac.html) listener endpoints. 

A couple similar examples:
 - https://github.com/louislam/uptime-kuma/issues/139
 - https://github.com/statping/statping/issues/597

**Comment by luciofsl** [comment]
@TwiN any update for this feature? It would be great to have this working...

**Comment by TwiN** [comment]
Sounds like an excellent feature to add in https://github.com/TwiN/gatus#client-configuration
