### ISSUE TITLE
Unable to parse JSONPath with array

### ISSUE THREAD

**Issue by Cartache** [TwiN/gatus#195]
Hi, I tried everything I could to solve this by myself but was unable to find the right condition.
The condition is to check  if account 1 is registered.

`{
  "success" : true,
  "result" : {
    "accounts" : [
      {
        "account" : 1,
        "sipNumber" : "1000",
        "registered" : true,
        "registerTime" : 1635892052
      },
      {
        "account" : 2,
        "sipNumber" : "1000",
        "registered" : false
      }
    ]
  }
}`

![image](https://user-images.githubusercontent.com/46925770/140032509-fee299ec-0638-42fa-af33-a7c6f9cb8c00.png)

My condition is written as follows:

`    conditions:
      - "[STATUS] == 200"  
      - "[BODY].result.accounts[0].registered == true"`
I am getting an error stating that "Couldn't walk through 'account[0]' because type was '<nil>' but expected 'map[string]{interface}'

A little help would be appreciated.

**Comment by TwiN** [comment]
Hello @Cartache,

Looks like you might have to restart your instance; the error says `account[0]` but your configuration shows you using `accounts[0]`.

**Comment by Cartache** [comment]
Hi TwiN,

Thank you for your rapid answer. I think it was a typo from me but restarted docker container. Now I get a different error:
![image](https://user-images.githubusercontent.com/46925770/140027417-3a377c76-6634-49c4-bf88-b670140fb5b6.png)

**Comment by Cartache** [comment]
Just for your information, the error message in my first comment is a re-transcript, the second on an print screen image.

**Comment by Cartache** [comment]
I continue to test and noticed that even the simple condition as follows returns a wrong answer:

`    conditions:
      - "[STATUS] == 200"  
      - "[BODY].success == true"
`
![image](https://user-images.githubusercontent.com/46925770/140032392-a43470d1-6456-4788-a118-2135d39f4ea7.png)

**Comment by Cartache** [comment]
The problem definitely lies in the result returned containing an array.

I tested the same server with 2 different API Requests, one with and another without array, and the one without returns the correct answer when the one with the array returns an error **### for the same data retrieved**

API 1 with an array:
![image](https://user-images.githubusercontent.com/46925770/140045579-6e688f30-d296-4d0f-b718-1cff41d6635c.png)
API 2 without array:
![image](https://user-images.githubusercontent.com/46925770/140045767-a79398e2-7ffb-4e9c-b29d-5eb81b8077d3.png)

The configuration:
![image](https://user-images.githubusercontent.com/46925770/140046258-45737171-59f8-44ff-b294-f5afb2e5dee5.png)

The result:
![image](https://user-images.githubusercontent.com/46925770/140046415-f9bcc972-dfb7-411a-b393-117d73baa4c4.png)
![image](https://user-images.githubusercontent.com/46925770/140046529-a3d78dbb-525d-4b23-8f1d-690e483d88ce.png)

**Comment by TwiN** [comment]
I suspect that your first endpoint (`Intercom`) is not returning the body that you think it might.

The easiest way to debug an issue with the body is to make an obviously incorrect condition containing the `[BODY]` on one side.

For instance:
```yaml
  - "[BODY] == lol"
```

This will cause the condition on the UI to be resolved to
```yaml
`[BODY] ({"success": false, "result": {...) == lol`
```
The resolved condition will be truncated on the UI, but you should still be able to extract some useful information when you hover over the failing result on the UI.

**Comment by Cartache** [comment]
Hi,
Thank you again for your reactivity. 
I managed to make it work after lots of tests, trials & errors (_this, based on your last suggested debug method:    - "[BODY] == lol"_).
I thought it would be interesting for other people struggling like me with API RESTful calls with responses containing arrays to share a useful example (useful I think :-)) 

For an JSon answer of this type 
{
    "success": true,
    "result": {
        "accounts": [
            {
                "account": 1,
                "sipNumber": "1000",
                "registered": true,
                "registerTime": 1636719013
            },
            {
                "account": 2,
                "sipNumber": "1000",
                "registered": false
            }
        ]
    }
}

The correct condition format would be:
      - "[STATUS] == 200"
      - "[BODY].success == true"      
      - "[BODY].result.accounts[0].sipNumber == 1000"      
      - "[BODY].result.accounts[0].registered == true"      

![image](https://user-images.githubusercontent.com/46925770/141469324-5d4e0078-d973-4313-8a44-e7c3e90b40d7.png)

Regards and thank you again for this wonderful piece of work.

Cartache
