### ISSUE TITLE
Support OpenID Connect for auth 

### ISSUE THREAD

**Issue by mTLamouchi** [TwiN/gatus#205]
How  I can secure the gatus api with open id connect, any suggestion for good openId libraries in golang

**Comment by TwiN** [comment]
I'd love to add support for OIDC, alas, I've barely ever played with OAuth2, much less OpenID.

**Comment by TwiN** [comment]
Duplicate of #158

**Comment by TwiN** [comment]
Released in [v3.5.0](https://github.com/TwiN/gatus/releases/tag/v3.5.0)

**Comment by xeruf** [comment]
See:
- https://twin.sh/articles/56/securing-gatus-with-oidc-using-auth0
- https://github.com/TwiN/gatus#oidc

You should link to the readme from gatus.io as it took me a while to locate the documentation there ^^
