### ISSUE TITLE
Events no more updated after upgrade from 3.1.0 to 3.3.3

### ISSUE THREAD

**Issue by philippe-granet** [TwiN/gatus#206]
After upgrade from 3.1.0 to 3.3.3, I continue to have mattermost notification, but Events list is not updated in web UI

**Comment by TwiN** [comment]
Are you persisting your data in a file?
If yes, somebody mentioned something similar in https://github.com/TwiN/gatus/issues/191#issuecomment-950444288 but it should've been fixed in v3.3.1 🤔

**Comment by philippe-granet** [comment]
@TwiN Yes, I use Docker image `twinproduction/gatus:v3.3.6` and my configuration:
```
    storage:
      type: sqlite
      path: /data/gatus.db
```

**Comment by TwiN** [comment]
What happens if you rename you try with a different, empty sqlite file?

**Comment by philippe-granet** [comment]
@TwiN I clean all and restart, and now all works fine.  
I will open a new issue if I reproduce the problem.
