### ISSUE TITLE
Email/SMTP alerting provider

### ISSUE THREAD

**Issue by Korijn** [TwiN/gatus#208]
Would be nice to be able to hook this up to e.g. twilio sendgrid or a generic SMTP server for alerting. Chatops is not really a thing in my team.

**Comment by TwiN** [comment]
Duplicate of #117 

👍 The aforementioned issue if you want to increase the odds that it'll be prioritized.

**Comment by TwiN** [comment]
FYI, this will be implemented very soon (see #210)

**Comment by TwiN** [comment]
Released in [v3.4.0](https://github.com/TwiN/gatus/releases/tag/v3.4.0)
