### ISSUE TITLE
How to consume metrics

### ISSUE THREAD

**Issue by Korijn** [TwiN/gatus#209]
I'm struggling with querying and visualizing the exposed metrics in grafana. Ideally I convert them to something useful like big green/red lights that indicate for every endpoint if it is up or not, and I can set up alerting based on the prometheus metrics as well, just to have everything in one place.

Do you have any examples or reference material I could look at to learn more?

In particular what I find challenging is that the `success` property is a label, instead of the value, of the time series. So there actually appear to be two series (success true, success false) for a single endpoint, which is really confusing to me. How do I properly query/consume this?

**Comment by TwiN** [comment]
Hello @Korijn,

To be honest, metrics isn't something I put a lot of efforts on, so don't expect much.

That being said, you can see an example at https://github.com/TwiN/gatus/blob/master/.examples/docker-compose-grafana-prometheus/grafana/provisioning/dashboards/main.json

**Comment by TwiN** [comment]
I added some examples of query in https://github.com/TwiN/gatus/blob/master/.examples/docker-compose-grafana-prometheus/README.md

**Comment by xeruf** [comment]
Uptime Kuma has a nice guide with Prometheus and Grafana, maybe this can be handy here, too ;) https://github.com/louislam/uptime-kuma/wiki/Prometheus-Integration

**Comment by TwiN** [comment]
@xeruf There's an example at https://github.com/TwiN/gatus/tree/master/.examples/docker-compose-grafana-prometheus, as linked in https://github.com/TwiN/gatus#metrics
