### ISSUE TITLE
feat(ui): Make logo link and header configurable

### ISSUE THREAD

**Issue by janhoy** [TwiN/gatus#213]
We can now configure `ui.title` and `ui.logo` but there should also be a `ui.headline` to customize the text "Health Status". We have several environments and would be nice to have the env. name in the main headline, e.g. "MyApp production A status".

**Comment by TwiN** [comment]
That, and I also plan on adding a configuration for:
- support email address (to display somewhere on the page)
- support phone number (to display somewhere on the page)
- link to a website (to display somewhere on the page + on logo click)

**Comment by finzzz** [comment]
Hello,.. Is there any plan to implement this in near future?

**Comment by TwiN** [comment]
@finzzz Definitely. 

Side note, `header` or `headline`?

**Comment by finzzz** [comment]
I need link to a website, so that gatus can act as a dashboard page as well.

**Comment by TwiN** [comment]
Release in [v3.5.0](https://github.com/TwiN/gatus/releases/tag/v3.5.0)
