### ISSUE TITLE
build(docker): Add support for armv8

### ISSUE THREAD

**Issue by jtagcat** [TwiN/gatus#235]
I'm not sure what exactly I need. I just know what is available wasn't enough.
```sh
$ uname -m
aarch64
```

This likely involves adding `linux/arm/v8` to https://github.com/TwiN/gatus/blob/master/.github/workflows/publish-release.yml

I'm not really sure what arch I have, and if v8 and aarch64 are synonyms.

I can't easily test this, so I'm not going to assign this to myself atm.

***
Astetiks++ workaround:
```
  gatus:
    build: https://github.com/TwiN/gatus.git
    image: twinproduction/gatus:latest
```

**Comment by TwiN** [comment]
Pretty sure the issue is that you're using latest.

If you want to use arm, you'll have to use a version tag (e.g. `twinproduction/gatus:v3.5.0`)

**Comment by jtagcat** [comment]
You are correct. Though, `:v3` or similar would be a nice tag to have in parallel.
