### ISSUE TITLE
feat(alerting): Add link to Gatus dashboard in the alerts

### ISSUE THREAD

**Issue by kpolischuk** [TwiN/gatus#236]
### Describe the feature request

Add link to gatus dashboard in alert message

[example](https://github.com/kpolischuk/gatus/commit/2b781df8dac9ee8f4ceb834d68dd12d282dd12f8#diff-1151907af26d6a4976d63775b1fe58a11f0f10854aed095e63c677905b615f10)

**Comment by TwiN** [comment]
See https://github.com/TwiN/gatus/pull/234#discussion_r783506845 for reference

**Comment by TwiN** [comment]
I'm going to close this in favor of the `[ENDPOINT_URL]` placeholder that #287 would implement.
