### ISSUE TITLE
Incorrect display of event time 

### ISSUE THREAD

**Issue by danilvoe** [TwiN/gatus#243]
### Describe the bug

The time on the general dashboard is displayed taking into account the time zone, and the time of the event in the cards is displayed without taking into account the time zone. 

### What do you see?

![Screenshot_1147](https://user-images.githubusercontent.com/15100792/152298729-7e08a788-7e85-473b-8320-0c4d71755250.png)
![Screenshot_1146](https://user-images.githubusercontent.com/15100792/152298731-bc442a5d-8712-472c-b051-5dde437530b0.png)
![Screenshot_1145](https://user-images.githubusercontent.com/15100792/152298734-510ca12e-fe75-4c7a-8beb-9807d73dddaf.png)

### What do you expect to see?

It is necessary either to take into account the time zone everywhere or ignore it just the same everywhere.
Of course, it is better to take into account the time zone, since the water place is already displayed correctly

### List the steps that must be taken to reproduce this issue

1. Put the site on monitoring
2. Make trigger conditions
3. Return conditions so that the trigger becomes inactive
4. Check the time on the dashboard and inside the card

### Version

3.5.0

**Comment by TwiN** [comment]
Oh yuck, inconsistencies.

Thank you for bringing this up, I'll fix it ASAP :)
