### ISSUE TITLE
Checking certificate lifetime in days?

### ISSUE THREAD

**Issue by danilvoe** [TwiN/gatus#246]
### Describe the bug

Today I received a notification about an expired certificate and complaints about a non-working site, I was very surprised.

I looked at the configuration documentation and noticed that the examples are indicated in hours, and I indicated in days.

Gatus interpreted 15d as 15 minutes?

### What do you see?

![1644145780623](https://user-images.githubusercontent.com/15100792/152678510-644100f8-23f6-488c-83df-e79c26d40456.JPEG)
![1644145780653](https://user-images.githubusercontent.com/15100792/152678511-4633e7c0-01e1-480a-b96a-f7be83fbd991.JPEG)
![1644145780673](https://user-images.githubusercontent.com/15100792/152678512-d4d17841-b8c6-465d-ab0f-63915c27a2ec.JPEG)

### What do you expect to see?

If Gatus does not support specifying y days, then there should be a startup error, similar to when there is an error in the configuration. In the parameter description, explicitly specify the supported units (hours, days, weeks)

### List the steps that must be taken to reproduce this issue

1. Set up verification as "[CERTIFICATE_EXPIRATION] > 14d"
2. Wait for the expiration date of the certificate :)

### Version

3.5.0

**Comment by TwiN** [comment]
Hello @danilvoe!

By default, Go's `time.Duration` only supports units up to `h` for hours (e.g. 2h3m4s). As such, the unit `d` is not a valid unit.
If you look at the [documentation on placeholders](https://github.com/TwiN/gatus#placeholders), you'll notice that the examples for `[CERTIFICATE_EXPIRATION]` are `24h` and `48h` (instead of 1d and 2d).

That said, I do think specifying this in the documentation would be a great idea. 

Would you like to make a PR?

**Comment by danilvoe** [comment]
> Hello @danilvoe!
> 
> By default, Go's `time.Duration` only supports units up to `h` for hours (e.g. 2h3m4s). As such, the unit `d` is not a valid unit. If you look at the [documentation on placeholders](https://github.com/TwiN/gatus#placeholders), you'll notice that the examples for `[CERTIFICATE_EXPIRATION]` are `24h` and `48h` (instead of 1d and 2d).
> 
> That said, I do think specifying this in the documentation would be a great idea.
> 
> Would you like to make a PR?

Unfortunately no. English raises questions for me. :( Better someone with a normal knowledge of the language will correct the documentation. :(
