### ISSUE TITLE
PagerDuty integration to get incident updates

### ISSUE THREAD

**Issue by tyagian** [TwiN/gatus#249]
### Describe the feature request

Hi,

Does it integrate with PagerDuty webhook to get incident updates from it?
Or if you know there is any way to do that?

### Why do you personally want this feature to be implemented?

Yes. I used few products in past but none of those offer this feature as far as I found. Want to check before going ahead with starting to build my own.

**Comment by TwiN** [comment]
What do you mean by "incident updates"?

I assume you're asking whether any update about an ongoing incident on PagerDuty is reflected on Gatus' status page - unfortunately, it is not currently the case.

I do plan on adding support for incident updates soon, but not yet :)
