### ISSUE TITLE
feat: Provide API support to execute all endpoints under a group

### ISSUE THREAD

**Issue by mani9223-oss** [TwiN/gatus#252]
### Describe the feature request

Provide API support to execute all endpoints under a group.

Endpoints are executed at certain intervals, but if a user wants to execute all endpoints under a group, this feature would be useful so that the user need not wait for the next execution.

In addition to this, we can also have a button in UI to do this for every group.

### Why do you personally want this feature to be implemented?

Endpoints are executed at certain intervals, but if a user wants to execute all endpoints under a group, this feature would be useful so that the user need not wait for the next execution.

In addition to this, we can also have a button in UI to do this for every group.

**Comment by mani9223-oss** [comment]
@TwiN Any thoughts on this feature?

**Comment by TwiN** [comment]
I can see how that would be useful, but this would probably require a more serious authentication system, wouldn't it?

I do think it's a great idea, though 🤔

**Comment by mani9223-oss** [comment]
Thanks, @TwiN . Yes, since this would be a POST request, we certainly need an authentication system.

**Comment by mani9223-oss** [comment]
@TwiN Would you consider implementing this?

**Comment by TwiN** [comment]
This is not something I will be adding in the foreseeable future, though perhaps a future API would enable a similar feature.
