### ISSUE TITLE
feat(web): HTTPS/TLS support

### ISSUE THREAD

**Issue by chr1st1ank** [TwiN/gatus#253]
### Describe the feature request

It looks like the Gatus service does not support serving over an encrypted connection by itself. Instead one would need to add a reverse proxy in front to enable HTTPS. It would be great if one could specify the path of TLS certificates and Gatus would then offer the endpoints over an encrypted connection.

### Why do you personally want this feature to be implemented?

HTTPS has become the standard for web services. Especially if any kind of credentials are involved encryption is necessary.  And Gatus supports HTTP basic auth - which is very unsecure in the absence of encryption. Using an external proxy makes the deployment unnecessarily complicated.

### Additional information

Enabling HTTPS might not be complicated. Here is an example: https://gist.github.com/denji/12b3a568f092ab951456

**Comment by TwiN** [comment]
That's a good point. To be honest, I built Gatus with Kubernetes in mind, which implies a reverse proxy/ingress controller (or even a load balancer) that takes care of TLS termination, so I never bothered thinking about it as a fully stand-alone application from end to end.

I don't know when I'll be able to work on it due to how busy I am lately though, so if you or anybody wants to take a shot at it, by all means 🙏

**Comment by chr1st1ank** [comment]
Thanks for the response. No worries, just opened the feature request because I found it logical to have in the backlog. Maybe I try a PR indeed at some point. But for now I added an nginx reverse proxy which handles TLS.

**Comment by Darkvater** [comment]
following, have the same issue here. Cannot connect to any status-page requiring a cert as it says "remote error: tls: bad certificate". As this feature is critical I might have a go at getting it done myself, will share a pull-request if done.

**Comment by iamdempa** [comment]
Is this released?

**Comment by TwiN** [comment]
@iamdempa No, otherwise the issue would have been closed :P

**Comment by ndlanier** [comment]
I'll add my +1 to wanting this feature.

Great tool though @TwiN, the simplicity and scalability with this is amazing and can't wait to see how this project grows.

**Comment by razermuse** [comment]
Personally, I think there are likely more important features to implement than SSL support in the short term. I use NGINX with Let's Encrypt and it works great.

**Comment by chr1st1ank** [comment]
Well, it is easier to implement than to configure nginx. Also, if you work with containers, you need to have two and to configure the container networking properly. It is possible, I'm also using it like this, with docker-compose, but this is such an easy catch that I don't see the point.

The implementation is also already done in #322. It just went out of sync while waiting for a final review 🤷‍♂️
