### ISSUE TITLE
Application not starting after migrating database to a new DB instance

### ISSUE THREAD

**Issue by mani9223-oss** [TwiN/gatus#258]
### Describe the bug

I have tried to migrate our data to a new DB instance and the application is not starting after migration. I am using PSQL as my DB.

**Steps:**
- Connect to existing DB using pgAdmin
- Take a backup of gatus DB
- Restore the data to the new DB instance and start the application

### What do you see?

Application stuck with following logs,
```
2022/03/04 15:03:26 [config][Load] Reading configuration from configFile=config/config.yaml
2022/03/04 15:03:26 [config][validateAlertingConfig] Alerting is not configured
2022/03/04 15:03:26 [config][validateEndpointsConfig] Validated 4 endpoints
```

### What do you expect to see?

Application should start normally

### List the steps that must be taken to reproduce this issue

- Connect to existing DB using pgAdmin
- Take a backup of gatus DB
- Restore the data to the new DB instance and start the application

**Comment by TwiN** [comment]
What do the logs look like if you have `debug` set to `true` in your `config.yaml` file?

**Comment by mani9223-oss** [comment]
@TwiN Debug logs just returning the endpoint names.

```
2022/03/05 05:46:51 [config][Load] Reading configuration from configFile=config/config.yaml
2022/03/05 05:46:51 [config][validateAlertingConfig] Alerting is not configured
2022/03/05 05:46:51 [config][validateEndpointsConfig] Validating endpoint 'CM'
2022/03/05 05:46:51 [config][validateEndpointsConfig] Validating endpoint 'PPM'
2022/03/05 05:46:51 [config][validateEndpointsConfig] Validating endpoint 'DOCGEN - 00-BLDINT-04-00'
2022/03/05 05:46:51 [config][validateEndpointsConfig] Validating endpoint 'MM - 00-BLDINT-04-00'
2022/03/05 05:46:51 [config][validateEndpointsConfig] Validated 4 endpoints
```

**Comment by TwiN** [comment]
What does your configuration look like? You can hide some information, but I'm not able to reproduce your issue.

**Comment by mani9223-oss** [comment]
Thanks for checking this @TwiN. Yeah, this is my config. Did you follow the same steps as me?
```
ui:
  title: <title>
  header: <header>
  link: <link>

debug: true
storage:
  type: postgres
  path: >-
    postgres://<uname>:<pwd>@<NEW_DB_IP>:5432/<DB_NAME>?sslmode=disable

endpoints:
  - name: <name>
    group: <group>
    url: <URL>
    interval: 5m
    conditions:
      - '[STATUS] == 200'
      - '[RESPONSE_TIME] < 30000'


```

**Comment by mani9223-oss** [comment]
@TwiN It's working for me now. I didn't do anything. But yeah I have successfully migrated to a DB and the app is running. So, I am closing this issue. Thanks for your support.

**Comment by TwiN** [comment]
@mani9223-oss Cheers, I'm glad everything worked out for you in the end!
