### ISSUE TITLE
Basic Auth for HTTP endpoint

### ISSUE THREAD

**Issue by 12nick12** [TwiN/gatus#260]
### Describe the feature request

Allow gatus to connect to sites using basic auth

### Why do you personally want this feature to be implemented?

So I can test connecting to site with basic auth

### How long have you been using this project?

7 days

### Additional information

This is pretty awesome, thank you.

**Comment by TwiN** [comment]
Hey @12nick12!

You can already do this by using headers.

Have a look at #200.
