### ISSUE TITLE
Add degraded state option

### ISSUE THREAD

**Issue by JayFromProgramming** [TwiN/gatus#261]
### Describe the feature request

A degraded state in addition to up/down to allow for alerting for things begging to go wrong before they have gone wrong, an example would be if the response time has exceeded a set amount but the service is still up the service would just be degraded and not defined as completely down. 
![image](https://user-images.githubusercontent.com/46631427/158251029-9e407b7c-087a-4d6d-8686-e48874dfae1f.png)

Preferably each check could be defined as CRITICAL or ALERT as this would allow for the most customizability in alerts so you could have separate "Everything is on fire " and  "You should look at this" alerts 

### Why do you personally want this feature to be implemented?

I would personally desire to have this feature implemented because I not only use gatus to monitor status of services but also the status of individual machines in my cluster (CPU usage, MEM usage, ect). An it would be really useful to have one combined option for knowing if one of my nodes is just heavily loaded vs completely down.   Currently its technically possible by having 2 separate endpoint objects with different state checks and alerts but its just very clunky and not user-friendly.  

### How long have you been using this project?

about 6 months

### Additional information

I am aware of issue #149 but that in my opinion hasn't resolved the issue of a Critical Vs Non Critical option, it only allowed multiple checks per service.

**Comment by TwiN** [comment]
I feel this may be a duplicate of #227. What do you think?

**Comment by JayFromProgramming** [comment]
It does appear to be a duplicate, my bad I didn't see that issue before I posted mine.

**Comment by TwiN** [comment]
@JayFromProgramming No worries!
