### ISSUE TITLE
Using a DNS server other than the system one

### ISSUE THREAD

**Issue by danilvoe** [TwiN/gatus#273]
### Describe the feature request

The ability to use a dns server other than the system server for monitoring.
Implementation example  https://koraygocmen.medium.com/custom-dns-resolver-for-the-default-http-client-in-go-a1420db38a5d

### Why do you personally want this feature to be implemented?

At the moment, Gatus is running in the cloud (docker) inside which the container itself is with Gatus. This design makes it difficult to configure DNS at the OS level.

**Comment by mapl** [comment]
> The ability to use a dns server other than the system server for monitoring.
You actually can specify the dns server to use
see https://github.com/TwiN/gatus#monitoring-an-endpoint-using-dns-queries

**Comment by TwiN** [comment]
I believe @danilvoe is talking about the DNS server to use for non-DNS endpoints (e.g. HTTP) to, for instance, perform the hostname lookup.

**Comment by danilvoe** [comment]
Works great! (just now had a chance to check in action)
