### ISSUE TITLE
Add progress bar for APIs loading at the backend

### ISSUE THREAD

**Issue by mani9223-oss** [TwiN/gatus#275]
### Describe the feature request

We need to show the progress bar while loading APIs at the backend. For instance, this API` api/v1/endpoints/statuses?page=$pageNumber` is taking 10 to 15 seconds for me, and I feel it's better to show a progress bar to say that the page is loading something at the backend.

### Why do you personally want this feature to be implemented?

I have more than 300 endpoints in 9 groups. For me this API `api/v1/endpoints/statuses?page=$pageNumber` is taking 10 to 15 seconds. I know there is something loading at the backend, but others feel the page is staying idle for a few secs. 

We can also block the `next` and `previous` buttons during this page load which will prevent users from sending multiple requests to DB.

### How long have you been using this project?

3 months

**Comment by TwiN** [comment]
That'd definitely be an improvement UX-wise.

Another feature that might help with this, though, is implementing paging for endpoints (see #150).

**Comment by TwiN** [comment]
I finally gave in after seeing yet another configuration with >100 endpoints.

I personally never thought that so many people would use Gatus to monitor a _significant_ amount of endpoints, but hey, that's a good thing as far as I'm concerned. I'll be rolling out an update which will add a loading animation while the data is retrieved in a few minutes.
