### ISSUE TITLE
Provide a way to troubleshoot `[BODY]` conditions

### ISSUE THREAD

**Issue by tiwood** [TwiN/gatus#298]
### Describe the feature request

We have some checks where we use a `[BODY]` condition. Sometimes the request seems to completely fail and the body cannot be parsed which results in failed condition like this:

![CleanShot 2022-06-27 at 5 48 58](https://user-images.githubusercontent.com/6249819/175981414-e3b63eb6-d381-465e-afa0-60162444be13.png)

It would be great if we could actually get the full response, either in the GUI or maybe just as STDOUT output.

It could be a additional option, which can be toggled:

```yaml
ui:
  additional-details-on-body-parse-errors: true
```

### How long have you been using this project?

8 months

**Comment by TwiN** [comment]
Would you be fine if if was just printed in the console if `debug` was set to `true`?

**Comment by heitorPB** [comment]
I am facing this exactly same issue.

It would be very helpful if we could see the full request (headers, url, body, params, etc) and the full return (headers, body, etc) somehow.

**Comment by heitorPB** [comment]
I came up with a bogus condition to show something, maybe it can help you @tiwood:

```yaml
    conditions:
      - "[BODY] == withheaders"
```

This condition shows the error received:

![gatus](https://user-images.githubusercontent.com/13461702/216668536-e0037da5-e4f0-4732-b0b8-f8fd2ec82811.png)

Now I need to figure out the correct syntax for this graphql query...

**Comment by TwiN** [comment]
As of 038c8c8d8e312c18dcbaeabc6d20b449cf3ad50f, the response body is now logged if `debug` is set to `true` and if the evaluation fails.

Since @tiwood agreed this would be sufficient for their use case, I'm going to close this.

@heitorPB if you think further improvements could be made, please create a new feature request.
