### ISSUE TITLE
Config via a new GATUS_CONFIG environment variable.

### ISSUE THREAD

**Issue by tostt** [TwiN/gatus#317]
### Describe the feature request

Currently, users can specify a custom path for the configuration file by setting the `GATUS_CONFIG_FILE` environment variable. That's nice.

Going further, to make life easier for users who have no control on the infrastructure (especially volumes), a new `GATUS_CONFIG` environment variable would be useful.
This variable would contain a valid configuration (i.e. the contents of a configuration file). If set, Gatus would use it directly without reading the config file.

### Why do you personally want this feature to be implemented?

The main reason is to make life easier :
- at configuration time : keeping the configuration with the docker-compose stack,
- at runtime: avoid having to create, keep track and manage a volume for a single file.

**Comment by TwiN** [comment]
Hello @tostt,

The problem with this is that some OS appear to have limitations on maximum number of bytes for environment variables.

That said, I'm not strictly against having such a feature, so if you'd like to implement it, feel free to create a PR.

**Comment by TwiN** [comment]
See https://github.com/TwiN/gatus/pull/318#issuecomment-1396512518
