### ISSUE TITLE
Allow to set HTML meta description

### ISSUE THREAD

**Issue by salim-b** [TwiN/gatus#345]
### Describe the feature request

It would be nice to be able to set the [`<meta name="description">`](https://web.dev/meta-description/) of Gatus' web frontend, e.g. via an additional config option `ui.description`.

### Why do you personally want this feature to be implemented?

It would increase the status page's machine-readability (meta description can be conceived as a kind of structured data) and increase the Lighthouse score. Currently, the latter [complains](https://web.dev/measure/?url=https%3A%2F%2Fstatus.votelog.ch) that the "Document does not have a meta description".

### How long have you been using this project?

3 days (awesome project! ❤️)

**Comment by TwiN** [comment]
See #342
