### ISSUE TITLE
fix: len([BODY]) does not work if the body is a JSON array

### ISSUE THREAD

**Issue by diamonddelt** [TwiN/gatus#359]
### Describe the feature request

I'd like to use the `len()` condition in a health check when the expected result from hitting my endpoint is a list without a root key, instead of an object.

Example payload:

`[{"foo": "bar"}, {"hello": "world"}]`

I'd like to write a check like:

`len([BODY]) == 2`

To ensure that the returned data contains exactly two elements.

### Why do you personally want this feature to be implemented?

This would help our implementation more effectively monitor endpoints with easier to read syntax.

### How long have you been using this project?

Over 1 year

**Comment by TwiN** [comment]
Good catch, this should be working.
I'll have a look at it.

**Comment by diamonddelt** [comment]
@TwiN Thank you for the quick turnaround - very much appreciated!
