### ISSUE TITLE
GoogleChat alerts are blank under certain conditions for ICMP endpoints

### ISSUE THREAD

**Issue by melsom** [TwiN/gatus#362]
### Describe the bug

When using ICMP and [CONNECTED] == true, whenever an endpoint fails, the Google Chat/Spaces App only sends a blank message with no data. 

### What do you see?

Nothing is displayed, it sends an empty message.

### What do you expect to see?

Full alert, like with HTTPS, which works just fine. This is ICMP only.

### List the steps that must be taken to reproduce this issue

Setup googlechat alert, have an ICMP endpoint fail.

### Version

latest branch

**Comment by TwiN** [comment]
@melsom I've made an attempt to fix it in #363, but I don't use Google Chat, so could you test it for me?
I've published the fix under the Docker image tag `experimental` (`twinproduction/gatus:experimental`).

**Comment by melsom** [comment]
Hello @TwiN - Tried your build now, and now we don't see any messages ICMP or HTTPS at all coming into our Google Chat Space. I have no way of debugging this myself unless you give me explicit instructions :) Hope you're able to solve it.

**Comment by melsom** [comment]
Here are the logs for you:

ICMP Endpoint:

2022/11/09 07:51:46 [watchdog][handleAlertsToTrigger] Sending googlechat alert because alert for endpoint=TEST ALERT with description='Endpoint is not responding' has been TRIGGERED
2022/11/09 07:51:46 [watchdog][handleAlertsToTrigger] Failed to send an alert for endpoint=TEST ALERT: call to provider alert returned status code 400: {
  "error": {
    "code": 400,
    "message": "Invalid value at 'message.cards[0].sections[0].widgets[2].key_value.content_multiline' (TYPE_BOOL), \"\"\nInvalid value at 'message.cards[0].sections[0].widgets[2].key_value.icon' (type.google                                                                                        apis.com/google.chat.v1.WidgetMarkup.Icon), \"\"",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "message.cards[0].sections[0].widgets[2].key_value.content_multiline",
            "description": "Invalid value at 'message.cards[0].sections[0].widgets[2].key_value.content_multiline' (TYPE_BOOL), \"\""
          },
          {
            "field": "message.cards[0].sections[0].widgets[2].key_value.icon",
            "description": "Invalid value at 'message.cards[0].sections[0].widgets[2].key_value.icon' (type.googleapis.com/google.chat.v1.WidgetMarkup.Icon), \"\""
          }
        ]
      }
    ]
  }
}

And for HTTPS:

2022/11/09 07:51:48 [watchdog][handleAlertsToTrigger] Sending googlechat alert because alert for endpoint=TEST ALERT 2 with description='Endpoint is not responding' has been TRIGGERED
2022/11/09 07:51:48 [watchdog][handleAlertsToTrigger] Failed to send an alert for endpoint=TEST ALERT 2: call to provider alert returned status code 400: {
  "error": {
    "code": 400,
    "message": "Invalid value at 'message.cards[0].sections[0].widgets[2].key_value.content_multiline' (TYPE_BOOL), \"\"\nInvalid value at 'message.cards[0].sections[0].widgets[2].key_value.icon' (type.google                                                                                        apis.com/google.chat.v1.WidgetMarkup.Icon), \"\"",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "message.cards[0].sections[0].widgets[2].key_value.content_multiline",
            "description": "Invalid value at 'message.cards[0].sections[0].widgets[2].key_value.content_multiline' (TYPE_BOOL), \"\""
          },
          {
            "field": "message.cards[0].sections[0].widgets[2].key_value.icon",
            "description": "Invalid value at 'message.cards[0].sections[0].widgets[2].key_value.icon' (type.googleapis.com/google.chat.v1.WidgetMarkup.Icon), \"\""
          }
        ]
      }
    ]
  }
}

**Comment by TwiN** [comment]
@melsom Could you try again? I made another change & re-released `experimental`.

**Comment by melsom** [comment]
@TwiN 

It now sends blank alerts for everything. No errors in the logs though:
022/11/10 08:04:34 [watchdog][handleAlertsToResolve] Sending googlechat alert because alert for endpoint=TEST with description='Endpoint is not responding' has been RESOLVED

See the following url for screenshot:
https://i.postimg.cc/CLsgTXwL/mon.png

**Comment by TwiN** [comment]
@melsom So I finally gave in and decided to set up Google Chat myself, but well.. it seems like you need to be a paid user to create webhooks, so it seems like you'll be stuck with me for a bit longer 🤣 

Anyways, I've made one more change.
Hopefully, third time's the charm 🤞

**Comment by melsom** [comment]
It was :) Finally working. Thank you!

**Comment by TwiN** [comment]
@melsom Glad to hear it! I'll merge #363 shortly :)

**Comment by melsom** [comment]
It seems I have spoken too soon, we still get ICMP endpoints with no data. Do you have telegram or anything else? I want to share the data we use but do not want to put that public.

**Comment by TwiN** [comment]
Before that, I just created #364 and re-released the tag `experimental` with only one change: it prints the GoogleChat request body.

Could you try again, and reply with the request body that shows as a blank message?

(don't forget to replace all confidential information by other, equivalent strings)

**Comment by melsom** [comment]
Sorry been a few busy days. Will test now shortly and report back.

**Comment by melsom** [comment]
Still does not output anything for icmp. Also tried tcp, same there, but https works. Tcp/icmp does report fine to our pushover (custom) instance.

**Comment by melsom** [comment]
If you want to share your email I can invite your account to a paid Space to test.

**Comment by TwiN** [comment]
@melsom Please do, that would be awesome.

Use the following gmail account: 

```
chris.nas.svr at gmail dot com
```

**Comment by TwiN** [comment]
So I did some debugging using the space you provided me, and the cause seems to be that Google Chat refuses to display an URL when the underlying link is not prefixed with https://. 

Because `tcp://` and `icmp://` endpoints aren't prefixed with `https://`, it just fails silently (and Google Chat even returns a 200!).

Fix incoming.
