### ISSUE TITLE
bug: Investigate flaky `TestStore_InsertCleansUpOldUptimeEntriesProperly` test

### ISSUE THREAD

**Issue by TwiN** [TwiN/gatus#388]
### Describe the bug

Sometimes, the `TestStore_InsertCleansUpOldUptimeEntriesProperly` test will fail

### What do you see?

https://github.com/TwiN/gatus/actions/runs/3723336201/attempts/1
```
 --- FAIL: TestStore_InsertCleansUpOldUptimeEntriesProperly (0.04s)
    sql_test.go:109: oldest endpoint uptime entry should've been ~5 hours old, was 4h59m40.064240509s
    sql_test.go:119: oldest endpoint uptime entry should've been ~5 hours old, was 4h59m40.068831372s
    sql_test.go:129: oldest endpoint uptime entry should've been ~8 hours old, was 7h59m40.073425836s
    sql_test.go:139: oldest endpoint uptime entry should've been ~239h0m0s hours old, was 238h59m40.0780609s
    sql_test.go:150: oldest endpoint uptime entry should've been ~8 hours old, was 7h59m40.08307097s
```

### What do you expect to see?

Test should pass

### List the steps that must be taken to reproduce this issue

1. Execute `TestStore_InsertCleansUpOldUptimeEntriesProperly` between `hh:59:30` and `hh:59:59`
2. Note how the test will fail

### Version

latest (master)

### Additional information

I suspect this has something to do with https://github.com/TwiN/gatus/blob/f6a621da285dd43b3207ec21e4101b4b11eff6c5/storage/store/sql/sql_test.go#L100

**Comment by tesibelda** [comment]
Hi, I think the problem is using Round in line 100 and Truncate in line 108. The Round function in line 100 is returning not the current hour but the next hour when time.Now() is near the end of the current hour. The code in https://play.golang.com/p/zuYV6SBb5ps may explain this better than my words. When running the code at 04:59:14 the Truncate function returns 5h but when executed at 04:59:47 it returns 4h. Hope this helps.

**Comment by TwiN** [comment]
@tesibelda Awesome catch!

I've confirmed that replacing 
https://github.com/TwiN/gatus/blob/f6a621da285dd43b3207ec21e4101b4b11eff6c5/storage/store/sql/sql_test.go#L100-L101

by 
```go
now := time.Now().Truncate(time.Hour)
```
works as intended!

Would you like to make a PR for the fix? 
I don't mind taking care of it at all, but since you've found the fix, the contribution is yours to take if you want it :)

**Comment by tesibelda** [comment]
Great. PR #418 created for this.
