### ISSUE TITLE
bug: Gatus crash with `panic: interface conversion: interface {} is map[string]interface {}, not []interface {}` when we try to validate a property value

### ISSUE THREAD

**Issue by Tohyo** [TwiN/gatus#391]
### Describe the bug

Hello,

We currently use Gatus at my work to monitor some applications and API. Thank you for your work on this project :+1:  
Few weeks ago we noticed a crash of our gatus monitoring. 
The crash occurred because one of the API we are monitoring was down and instead of responding the expected format that look something like this:
```
[
    {
        "name": "test",
        ...
    },
    {
        ...
    },
    ...
]
```
the api returned:
```
{
  "statusCode": 500, 
   "message": "Internal server error"
}
```

This seems to happen because we are trying to check the value of the property name with this condition: `"[BODY][0].name == test"`

### What do you see?

I see our gatus app stopping with this error message:

```
status-gatus-1  | panic: interface conversion: interface {} is map[string]interface {}, not []interface {}
status-gatus-1  | 
status-gatus-1  | goroutine 39 [running]:
status-gatus-1  | github.com/TwiN/gatus/v4/jsonpath.extractValue({0xc0002900c6?, 0x3?}, {0xbfef40?, 0xc00050c120})
status-gatus-1  |   /app/jsonpath/jsonpath.go:52 +0x4e7
status-gatus-1  | github.com/TwiN/gatus/v4/jsonpath.walk({0xc0002900c6, 0x8}, {0xbfef40, 0xc00050c120})
status-gatus-1  |   /app/jsonpath/jsonpath.go:24 +0xa5
status-gatus-1  | github.com/TwiN/gatus/v4/jsonpath.Eval({0xc0002900c6, 0x8}, {0xc000512000, 0x34, 0x200})
status-gatus-1  |   /app/jsonpath/jsonpath.go:18 +0x9c
status-gatus-1  | github.com/TwiN/gatus/v4/core.sanitizeAndResolve({0xc0005a20e0, 0x2, 0xcb3a51?}, 0xc0002f6300)
status-gatus-1  |   /app/core/condition.go:252 +0x730
status-gatus-1  | github.com/TwiN/gatus/v4/core.Condition.evaluate({0xc0002900c0, 0x18}, 0xc0002f6300, 0x0)
status-gatus-1  |   /app/core/condition.go:96 +0xa5
status-gatus-1  | github.com/TwiN/gatus/v4/core.(*Endpoint).EvaluateHealth(0xc000280750)
status-gatus-1  |   /app/core/endpoint.go:263 +0x4e5
status-gatus-1  | github.com/TwiN/gatus/v4/watchdog.execute(0xc000280750, 0x3?, 0xc0002cc440, 0x0, 0x1, 0x0)
status-gatus-1  |   /app/watchdog/watchdog.go:63 +0x155
status-gatus-1  | github.com/TwiN/gatus/v4/watchdog.monitor(0xc000280750, 0xc0002f27d0?, 0xb5d695?, 0x80?, 0xe7?, 0x29?, {0xe2fcd0, 0xc0002cc500})
status-gatus-1  |   /app/watchdog/watchdog.go:41 +0x5c
status-gatus-1  | created by github.com/TwiN/gatus/v4/watchdog.Monitor
status-gatus-1  |   /app/watchdog/watchdog.go:33 +0x20d
```

### What do you expect to see?

I expect gatus to keep working and display that the problematic API is currently down.

### List the steps that must be taken to reproduce this issue

I managed to reproduce the issue on local environment by doing: 

1. Updating the `config.yaml` file with this configuration:
```
endpoints:
  - name: Test debug API
    group: test-debug
    url: http://localhost:3002/test // For the purpose of the test this api return {"statusCode": 500, "message": "Internal server error"}
    interval: 10s
    conditions:
      - "[STATUS] == 200"
      - "[BODY][0].name == test"
```
2. Start Gatus
3. Gatus should stop with this error message: `panic: interface conversion: interface {} is map[string]interface {}, not []interface {}`

### Version

4.4.0

### Additional information

I tried to check what was going on, I managed prevent the app from crashing but I have 0 Go dev experience so my modification are probably not really good.

Let me know if there is something we are doing wrong or if you want me to open a PR with the code I updated, maybe that can help you

Thank you

**Comment by TwiN** [comment]
Thank you for reporting the issue; I'll have a look at it ASAP

**Comment by TwiN** [comment]
@Tohyo Excellent catch! I'm releasing v5.1.1 with the fix right now.

**Comment by Tohyo** [comment]
Thank you for the release, happy :santa:
