### ISSUE TITLE
bug: Default configuration path not working

### ISSUE THREAD

**Issue by Sumtin** [TwiN/gatus#400]
### Describe the bug

Container fails to load using `latest` from Docker Hub.  Running Docker on Synology NAS using locally bound config file.

### What do you see?

```
panic: configuration file not found
goroutine 1 [running]:
main.main()
	/app/main.go:19 +0x168
```

### List the steps that must be taken to reproduce this issue

1. Load `latest` from Docker Hub
2. Bind config using mount parameter: `--mount type=bind,source=/volume1/docker/gatus/config.yaml,target=/config/config.yaml`
3. Notice error above.
4. Redeploy container using `stable`
5. Everything works.

**Comment by TwiN** [comment]
Excellent catch. 

Fixed by 78dccc9

Also glad to see somebody else with a Synology NAS!
