### ISSUE TITLE
bug: Prometheus unable to scrape /metrics 

### ISSUE THREAD

**Issue by astraldawn** [TwiN/gatus#406]
### Describe the bug

Prometheus is unable to scrape metrics for `latest` (as of 90bb8f7b5f916e144d571c7bc471fe3d93262eff), no issue with `stable`

### What do you see?

In http://localhost:9090/targets, a single target with:

- State: `DOWN`
- Error: "INVALID" is not a valid start token

### What do you expect to see?

In http://localhost:9090/targets, a single target with:

- State: `UP`

### List the steps that must be taken to reproduce this issue

1. Run the example in https://github.com/TwiN/gatus/blob/master/.examples/docker-compose-grafana-prometheus
2. Go to http://localhost:9090/targets, the error message appears
3. Swap tag to `stable`
4. Error message disappears after a short while

### Version

latest (90bb8f7b5f916e144d571c7bc471fe3d93262eff)

### Additional information

Go to localhost:8080/metrics

- `latest`: attempts to download metrics.gz
- `stable`: plaintext page with prometheus metrics

**Comment by TwiN** [comment]
Excellent catch. 

This appears to be the root cause https://github.com/prometheus/client_golang/issues/622

I've recently enabled gzip compression on the entire router, and it seems like because `promhttp.Handler()` uses its own compression, it causes an issue.
