### ISSUE TITLE
feat: display full URL

### ISSUE THREAD

**Issue by razermuse** [TwiN/gatus#408]
### Describe the feature request

I use Gatus to monitor multiple web applications I use to demo my employer's software products. They're hosted on the same EC2 server on different ports. Gatus truncates the URL in my config and only displays the URL (not the port) on the status page. I would like to Gatus to display the full URL with the port and when clicked, open the page. Hover over text with the full URL would work too as long as the URL is clickable. 

### Why do you personally want this feature to be implemented?

I use Gatus to monitor multiple demo systems - this feature would help me identify what port is being used by the particular demo system in question and be able to easily open the main page. 

### How long have you been using this project?

About 1 - 2 weeks.

**Comment by TwiN** [comment]
What you see on the dashboard isn't meant to be a truncated version of your endpoint URL, it's meant to be the hostname. 

While for your specific case it does make sense to display the full URL, a lot of people test complex endpoints which may require headers, query parameters, tokens, etc., some of which cannot be conveyed through a simple link, especially for non-GET endpoints.

Should this be implemented where the current hostname is located (see image below), I believe it would mislead people in thinking that the links should all be clickable.

![hostname](https://user-images.githubusercontent.com/15699766/215381589-c47a016d-eef2-4055-b409-a424ba67b70a.png)

As such, I will instead defer to an existing feature request which would allow the configuration of links (you've already commented on it, so I assume you're aware, but I'm posting it again for verbosity in case other people have the same requirement): #106
