### ISSUE TITLE
Support auth for ntfy alerts

### ISSUE THREAD

**Issue by thespad** [TwiN/gatus#419]
### Describe the feature request

ntfy supports access control and authentication for reading and writing messages https://docs.ntfy.sh/publish/#authentication

### Why do you personally want this feature to be implemented?

Supporting this would allow a publicly-exposed ntfy instance to relay Gatus alerts without any risk of 3rd parties guessing the topic and abusing it,

### How long have you been using this project?

~2 years

**Comment by OskarCarl** [comment]
I've created a pull request for this, at least to utilize [access tokens](https://docs.ntfy.sh/publish/#access-tokens).
Alternatively, you can use the `auth` paramter like this: `url: "<url>/?auth=<base64-auth>"`. It's documented [here](https://docs.ntfy.sh/publish/#query-param).
