### ISSUE TITLE
Get duplicate alert when Kubernetes deployment Replica set to 2 

### ISSUE THREAD

**Issue by gnande** [TwiN/gatus#421]
@TwiN Hi,
I receive every time 2 alerts (That is duplicate alert) on Google chat when kubernetes deployment Replica set to 2. As there are 2 gatus pods running in my cluster it sends me 2 duplicate alert message. Ideal scenario would be only one.
It should send only "one" alert message in internal google chat irrespective of how many gatus pods I am running in cluster.
Let me know how I can fix this ? Is there any separate flag for this ?
Below is the config map file I am using.

----

apiVersion: v1
data:
  config.yaml: |
    metrics: true
    alerting:
      googlechat:
        webhook-url: "https://chat.googleapis.com/v1/spaces/****/messages?key=****"
        method: "POST"
        default-alert:
          enabled: true
          send-on-resolved: true
          failure-threshold: 2
          success-threshold: 2
        client:
           insecure: true
        body: |
          {
            "text": "[ALERT_TRIGGERED_OR_RESOLVED]: [ENDPOINT_GROUP] - [ENDPOINT_NAME] - [ALERT_DESCRIPTION]"
          }
        overrides:
          - group: "PROD"
            webhook-url: "https://chat.googleapis.com/v1/spaces/****/messages?key=****"
          - group: "DEV"
            webhook-url: "https://chat.googleapis.com/v1/spaces/****/messages?key=****"
          - group: "TEST"
            webhook-url: "https://chat.googleapis.com/v1/spaces/****/messages?key=****"

   endpoints:
      - name: abc-service
        group: PROD
        url: "https://(mywebsite)/abc-service"
        interval: 5m
        conditions:
          - "[STATUS] == 200"
          - "[RESPONSE_TIME] < 1000"
          - "[CERTIFICATE_EXPIRATION] > 14d"
          - "[CONNECTED] == true"
        alerts:
          - type: googlechat

**Comment by TwiN** [comment]
Gatus does not currently support scaling horizontally, meaning you cannot have more than one replica -- the workload will not be shared nor will a leader be automatically elected.

In other words, if you have 2 replicas, they're effectively behaving as two separate Gatus instances.

**Comment by gnande** [comment]
Ok. Thanks for the update @TwiN !
