### ISSUE TITLE
Support more sorting algorithms on the UI

### ISSUE THREAD

**Issue by michaelkrieger** [TwiN/gatus#425]
### Describe the feature request

Currently groups and the endpoints within each group are printed alphabetically.  There seems to be no way to influence the sort order, other than changing the names.

Adding a field 'sortorder' with an arbitrary integer to sort the UI by would allow me to customize that order. Ideally, it wouldn't need to be sequential (ie: four entries with 99,14,7,5 displays as 5,7,14,99).

### Why do you personally want this feature to be implemented?

This could be useful for:
1. showing "hops" in the order of dependency. Like "Home Switch" could be set to come before "Home Router" creating a waterfall of problems
2. Showing the load balancers at the top of a list of web servers

### How long have you been using this project?

5 weeks

**Comment by TwiN** [comment]
This is a great idea, but I'd like for #35 to be implemented first before we start thinking about more complex ways to sort (i.e. before we implement something like a sorting priority).

If you can, please comment on #35 with your suggestion 🙏
