### ISSUE TITLE
Gorilla mux project is archived

### ISSUE THREAD

**Issue by skhokhlov** [TwiN/gatus#468]
Gatus uses gorilla mux router was archived and no longer actively maintained https://github.com/gorilla#gorilla-toolkit. I think it's a good reason to find something else.

**Comment by TwiN** [comment]
Yeah, I was thinking of migrating to fiber at some point.

**Comment by Radictionary** [comment]
What about Chi router?

**Comment by TwiN** [comment]
@Radictionary Personally not a fan of Chi. If I'm going to look at a different library, I'd like for it to at least be faster than the previous implementation, and IIRC Chi is as slow or slower than mux (they both rely on net/http, after all).

fiber on the other hand is based off fasthttp, which is significantly faster and lighter than net/http.

That, and I've already started migrating to fiber locally, just haven't had much time on my hands lately.
