### ISSUE TITLE
gatus ingress created by helm is not opening in the browser (Issue #12083)

### ISSUE THREAD

**Issue by Subhasish5** [TwiN/gatus#481]
Hi Team,

I created a helmrelease by applying the helmrelease.yml file from my local in a given namespace and it created the pods, svcs and ingress as well.

The kubernetes pod is not running because it's failing crashloopbackoff and the ingress is not loading in the browser.

Can you help.

Nor we can get anything from the pod logs as the container is not creating properly as the pod is not able to start and endpoint is not getting assigned any ip address and hence ingress is not loading in the browser.

I request you to kindly assist me on this as we are blocked on production for this ??

Thanks and Regards,
Subhasish

**Comment by TwiN** [comment]
Your pod could be crashing for many reasons. I'd suggest starting by looking at the logs, and if there's nothing else, then the pod's yaml.

Unfortunately, anything beyond that help is not something I'm willing to provide for free, so you'll have to figure it out on your own.
