### ISSUE TITLE
gatus ingress created by helm is not opening in the browser

### ISSUE THREAD

**Issue by Subhasish5** [TwiN/gatus#482]
Hi Team,

I created a helmrelease by applying the helmrelease.yml file from my local in a given namespace and it created the pods, svcs and ingress as well.

The kubernetes pod is not running because it's failing crashloopbackoff and the ingress is not loading in the browser.

Can you help.

Nor we can get anything from the pod logs as the container is not creating properly as the pod is not able to start and endpoint is not getting assigned any ip address and hence ingress is not loading in the browser.

I request you to kindly assist me on this as we are blocked on production for this ??

I am willing to pay for this as well.

Thanks and Regards,
Subhasish

**Comment by TwiN** [comment]
See https://github.com/TwiN/gatus/issues/483#issuecomment-1553907110
