### ISSUE TITLE
Websockets support

### ISSUE THREAD

**Issue by heitorPB** [TwiN/gatus#492]
### Describe the feature request

We have many services that use websockets and we would like to monitor them as well.

We currently use Gatus to monitor HTTP (GETs and POSTs) and ICMP; but we don't monitor our websockets via Gatus.

### How long have you been using this project?

~6 months

### Additional information

I'd like to implement this :) Any suggestions, ideas, mentoring would be greatly appreciated.

**Comment by vax-r** [comment]
@heitorPB 
Hello, do you mind if I get a hand on it ?
I would like to try and implement this

**Comment by vax-r** [comment]
@heitorPB 
I would love to do !
