### ISSUE TITLE
Feat(alerting): threshold per number of endpoints

### ISSUE THREAD

**Issue by antoinekh** [TwiN/gatus#495]
### Describe the feature request

I use gatus in DC with sometimes a lot of endpoints.
They are organised by groups.

It would be nice to be able to configure alerts globally or per group with a threshold.

The threshold could be a % or a number of endpoints.

The goal is to only alert if x endpoints are down and only once.
If only one endpoint is down, nothing is sent.

### Why do you personally want this feature to be implemented?

To be notified only when there is a real problem, not when hosts are flapping for example.

### How long have you been using this project?

Months

**Comment by antoinekh** [comment]
Finally, it's simpler and more logical to use on alerting grafana.
In our environment, everything is returned in Prometheus metrics and displayed on dashboards.

**Comment by TwiN** [comment]
@antoinekh Would you mind sharing a screenshot of your dashboard & the JSON queries you're using?

**Comment by antoinekh** [comment]
![image](https://github.com/TwiN/gatus/assets/52744345/aaa1f5c2-52d4-4fb3-8731-247775f9e3b3)
![image](https://github.com/TwiN/gatus/assets/52744345/549fe097-9c33-42da-a75a-b541213bfe43)

I will probably add some custom metric to avoid using rates, rates does not work well when metrics are at different rate.
In my example http every 4 seconds and ICMP every second.

Something like
```
if result.Connected {
		resultConnected.WithLabelValues(endpoint.Key(), endpoint.Group, endpoint.Name, string(endpointType)).Set(1)
	}
else {
resultConnected.WithLabelValues(endpoint.Key(), endpoint.Group, endpoint.Name, string(endpointType)).Set(0)
	}
```

The gitlab json model
[json_model.txt](https://github.com/TwiN/gatus/files/11782403/json_model.txt)


It could certainly be improved, but for the moment it works well for our purposes.

**Comment by TwiN** [comment]
Awesome, thank you @antoinekh!

There's also another example at https://github.com/TwiN/gatus/tree/master/.examples/docker-compose-grafana-prometheus

**Comment by antoinekh** [comment]
It was inspired by your very good examples 😉
