### ISSUE TITLE
How to customize the alarm content? 

### ISSUE THREAD

**Issue by wonktondI** [TwiN/gatus#525]
### Describe the feature request

e.g. Email alerts
An alert for wasm_demo has been resolved after passing successfully 2 time(s) in a row

Alert description: wasm failed

Condition results:
✅ [STATUS] == 200

I want to customize the alert:)

**Comment by TwiN** [comment]
At the moment, you can only customize it via the alert description (`endpoints[].alerts[].description`).

You can get an idea of how the string is built by looking at the provider, e.g. https://github.com/TwiN/gatus/blob/a725e7e7700bd355ebeb1891b2f90fe0b78fba32/alerting/provider/email/email.go#L69-L91
