### ISSUE TITLE
Binding to IPv6 fails or binds to the wrong address

### ISSUE THREAD

**Issue by tesinormed** [TwiN/gatus#532]
# Description

When trying to bind to an IPv6 address, whether that may be `::` or a specified address (such as `fdac:8d3d:d2de:aaaa::7`), Gatus fails to start or binds to the wrong address.

# Observations

*Note: the port shown in the log messages will change because of dynamic port allocation.*

## Binding to a valid IPv6 address (with square brackets)

The program fails to start with the following log output.

stderr:
```
2023/07/23 00:16:46 [controller][Handle] Listening on [fdac:8d3d:d2de:aaaa::7]:28215
2023/07/23 00:16:46 [controller][Handle]failed to listen: listen tcp4: address fdac:8d3d:d2de:aaaa::7: no suitable address found
```

## Binding to `::` (with square brackets)
This allows the program to start. However, it binds to 0.0.0.0 (IPv4), as seen in the log output and `netstat`.

stderr:
```
2023/07/23 00:22:29 [controller][Handle] Listening on [::]:25694
```

stdout:
```
 ┌───────────────────────────────────────────────────┐ 
 │                   Fiber v2.46.0                   │ 
 │              https://127.0.0.1:25694              │ 
 │      (bound on host 0.0.0.0 and port 25694)       │ 
 │                                                   │ 
 │ Handlers ............ 26  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ................. 1 │ 
 └───────────────────────────────────────────────────┘ 
 ```
 
 netstat:
 ```
 # netstat --all --numeric --inet --inet6 --programs | grep ':25694'
tcp        0      0 0.0.0.0:25694           0.0.0.0:*               LISTEN      558986/gatus    
```

## Binding to a valid IPv6 address (without square brackets)

The program fails to start with the following log output.

stderr:
```
2023/07/23 00:27:06 [controller][Handle] Listening on fdac:8d3d:d2de:aaaa::7:25318
2023/07/23 00:27:06 [controller][Handle]failed to listen: listen tcp4: address fdac:8d3d:d2de:aaaa::7:25318: too many colons in address
```

## Binding to `::` (without square brackets)

The program fails to start with the following log output.

stderr:
```
2023/07/23 00:28:22 [controller][Handle] Listening on :::29233
2023/07/23 00:28:22 [controller][Handle]failed to listen: listen tcp4: address :::29233: too many colons in address
```

# Expectations

I expect Gatus to start and bind to the correct address, as it had done in v5.4.0.

# Steps to reproduce

Start the program with at least this configuration included:
```yaml
web:
  address: '<< INSERT IPv6 ADDRESS (eg ::, fdac:8d3d:d2de:aaaa::7) >>'
  port: << INSERT PORT >>
```

I do not know if the following is important:
```yaml
  tls:
    certificate-file: /etc/certificates/certificate.pem
    private-key-file: /etc/certificates/key.pem
 ```

The program will either fail to launch or use `0.0.0.0` instead of `::`.

# Version

v5.5.1, using the OCI image with Docker

**Comment by TwiN** [comment]
At the moment, having Gatus listen to IPv6 is not supported.

That said, I'm not particularly against the idea of adding support for that.
