### ISSUE TITLE
[Question] Is High Availibility an open?

### ISSUE THREAD

**Issue by vanhoutenbos** [TwiN/gatus#538]
Is it an option to activate High Availability?
We would like to make sure that gatus is never down on our cluster, at this moment we would deploy 2 charts with 2 chart names that monitor eachother but also each need their own configuration.
It would be nice to use a headless method or something like that with multiple working pods!

**Comment by TwiN** [comment]
Duplicate of #176 - feel free to comment on that issue (and react with a 👍 to show your interest in the feature)
