### ISSUE TITLE
[Question] Hosting on a Windows Server

### ISSUE THREAD

**Issue by vanhoutenbos** [TwiN/gatus#539]
Hi,

I could not find any documentation so I am assuming this does not work out-of-the-box but is there a method to deploy this as a service on a Windows Server?
We have some old servers outside of our cluster that want to install gatus on to monitor netwerk stability.
Unfortunately we cannot install things easily on it because the servers are air-gapped (intranet).
So running the 'development' application might not work for us.

**Comment by TwiN** [comment]
Sure, you can deploy it on a windows server using Docker.

Otherwise, you _could_ compile the executable yourself, but I'd recommend going with the Docker route.
