### ISSUE TITLE
DOMAIN_EXPIRATION is negative for *.cn domains

### ISSUE THREAD

**Issue by BallTzeng** [TwiN/gatus#548]
### Describe the bug

It seems all *.cn domains are not working as expected.

### What do you see?

<img width="1242" alt="image" src="https://github.com/TwiN/gatus/assets/90144995/96985495-5b23-4526-bf76-d26438c510ef">

### What do you expect to see?

positive DOMAIN_EXPIRATION

### List the steps that must be taken to reproduce this issue

- name: kj892.cn
   group: it-sa
   url: "https://kj892.cn"
   interval: 86400s
   conditions:
      - "[DOMAIN_EXPIRATION] > 720h"

**Comment by sashkab** [comment]
Not sure if this is related, but today tried to build and test gatus and following tests failed:

```text
#9 70.09 --- FAIL: TestGetDomainExpiration (0.73s)
#9 70.09     client_test.go:43: expected domain expiration to be higher than 0
#9 70.09     client_test.go:48: expected domain expiration to be higher than 0
#9 70.09     client_test.go:55: expected domain expiration to be higher than 0
#9 70.09     client_test.go:62: expected domain expiration to be higher than 0
#9 70.09 FAIL
```

**Comment by sashkab** [comment]
.ai and .im domains are also affected, it seems.

<img width="396" alt="image" src="https://github.com/TwiN/gatus/assets/868842/dcfd1736-282d-4904-8972-1c78c7766db8">

**Comment by TwiN** [comment]
I was able to replicate the issue for .cn - I've created a test to replicate it programmatically at https://github.com/TwiN/whois/pull/12

I don't have time to work on this right now, but at least this is a good starting point.

Thank you for reporting the issue

**Comment by Kaned1as** [comment]
@TwiN please, just need to bump whois version to 1.1.7 to resolve this

**Comment by TwiN** [comment]
Should be available from the latest container built & future tags.

**Comment by 01ste02** [comment]
Can you confirm that .se TLD is working? I have the latest container, but it is still reporting as negative for me.
