### ISSUE TITLE
error with group written in Cyrillic

### ISSUE THREAD

**Issue by danilvoe** [TwiN/gatus#587]
### Describe the bug

The group name contains characters in Cyrillic. An error occurs when going to the detailed data view(/statuses).

### List the steps that must be taken to reproduce this issue

1. set in the configuration file for the site being checked a group(Endpoint groups) whose name contains characters in Cyrillic.
2. launch Gatus
3. go to the detailed information page (statuses)

### Version

5.6.0

### Additional information

The error originally occurred when migrating to 5.2

**Comment by TwiN** [comment]
I understand your point, but in the foreseeable future, I plan on supporting English.

Supporting non-English languages, therefore potentially problematic characters for URLs, is not a problem I currently think is not important enough in the grand scheme of things (i.e. feature-wise) to prioritize.

I apologize for the inconvenience.

**Comment by danilvoe** [comment]
@TwiN Good afternoon.
It may be possible to consider additional titles for
endpoints[].name and endpoints[].group (endpoints[].name_url and endpoints[].group_url)?
It turns out that the user will have the opportunity to set one name for the visual part, and another in English for the URL. in my opinion, this will solve my problem and add more flexibility to the overall solution. When endpoints[].name_url and endpoints[].group_url are filled in, the address for the URL is formed using them, if not specified, then according to the current logic.
