### ISSUE TITLE
I want to 'bash' into gatus k8s pod

### ISSUE THREAD

**Issue by vanhoutenbos** [TwiN/gatus#590]
### Describe the feature request

I am trying to bash into a gatus pod so that I can try some commands from the CLI.
Example;
`kubectl exec -it gatus-{PODHASH} -- /bin/bash`

I believe this is by design in go-lang, eventhough i have no knowledge of golang at all.
I found this source which indicates its my design https://stackoverflow.com/questions/43314689/example-of-exec-in-k8ss-pod-by-using-go-client

Is it possible to add this 'Command' ?

### Why do you personally want this feature to be implemented?

We use bash / linux scripting in all pods, sometimes we just need to test something simple

### How long have you been using this project?

1year

**Comment by userbradley** [comment]
Why do you need to exec in to the pod? 

They are building the application with [scratch](https://support.snyk.io/hc/en-us/articles/360004012857-What-are-docker-scratch-based-images-) which doesnt have a shell.

Worst case you can build your own dockerfile and change it to 

```diff
# Build the go application into a binary
FROM golang:alpine as builder
RUN apk --update add ca-certificates
WORKDIR /app
COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o gatus .

# Run Tests inside docker image if you don't have a configured go environment
#RUN apk update && apk add --virtual build-dependencies build-base gcc
#RUN go test ./... -mod vendor

# Run the binary on an empty container
- FROM scratch
+ FROM alpine
COPY --from=builder /app/gatus .
COPY --from=builder /app/config.yaml ./config/config.yaml
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENV PORT=8080
EXPOSE ${PORT}
ENTRYPOINT ["/gatus"]
```

That may work

**Comment by vanhoutenbos** [comment]
Ah understandable! Thank you for the code I think this will be worth the try.

My reasoning is that I want to validate something, according to gatus UI a certain endpoint is not returning 200 OK but 403 Forbidden, but from all other locations and tools it works.
It might be because of the implementation of go to use gethttprequest instead of pinging it for example.
Or missing something that a header requires.

**Comment by TwiN** [comment]
While I understand your reasoning, including bash in Gatus' Docker image as well as other common binaries (curl, ping, etc.) would also increase the maintenance required on my end to avoid vulnerabilities and security risks, and that's something I would rather avoid.

As @userbradley mentioned, you can create your own image for Gatus if having bash is a requirement for you.

**Comment by 221bshashank** [comment]
I tried _+ FROM alpine_, but when trying to run this command "docker exec -it <id>/bin/bash". I am getting this error
**OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown**
FYI, container is running

**Comment by userbradley** [comment]
@221bshashank Alpine doesn't have bash.

Try /bin/sh in place of /bin/bash

**Comment by 221bshashank** [comment]
thanks @userbradley , I am able to have a look inside the container now, do you know where is the storage part, I want to persist the data

**Comment by userbradley** [comment]
So from my understanding only way to persist data on Gary's is via pgsql or sql


As far as I know, status is stored in ram? I think?


https://github.com/TwiN/gatus#storage

**Comment by 221bshashank** [comment]
actually I tried it but I was getting some port issue (https://github.com/TwiN/gatus/issues/565), so now I am trying to build my own image and mount the volume on it, that's why wanted to know where I can mount the volume on container to persist the data
