### ISSUE TITLE
fix(alerting): Make Microsoft Teams title customizable

### ISSUE THREAD

**Issue by 221bshashank** [TwiN/gatus#598]
### Describe the bug

I have integrated teams alerting system but the alert that I am getting is not as expected.
I am not getting the proper icon in the alert.

### What do you see?

![image](https://github.com/TwiN/gatus/assets/54362793/5a90a982-1034-42c2-82a5-99138ebbd0c1)

as you can see in this image icon is not getting resolved, I am getting some value "&#x1F6A8"

### What do you expect to see?

![image](https://github.com/TwiN/gatus/assets/54362793/56f785ec-2fb0-4aa3-84a9-f2ae193c268d)
I want to see like this, the proper icon

### List the steps that must be taken to reproduce this issue

configure teams alerting system

### Version

latest

### Additional information

@TwiN pls look into this bug

**Comment by Rodri9o** [comment]
I see the same.

**Comment by JamesHillyard** [comment]
I've also experienced this problem, it started when I updated teams a few weeks ago 😞

I'm not using the "Try the new Teams" feature although the same issue exists when I turn it on
![image](https://github.com/TwiN/gatus/assets/73830120/431aac46-62d9-411c-b3da-5f92594075fd)

**Comment by 221bshashank** [comment]
I think color code needs to be changed (https://github.com/TwiN/gatus/blob/de7256e671c3cc6106a154a8fd49df426f4ce56a/alerting/provider/teams/teams.go#L108), not sure

**Comment by amai2012** [comment]
I don't know what side is wrong on this since other similar tools also got broken notifications...

This topic was recently reported at Microsoft at https://techcommunity.microsoft.com/t5/microsoft-teams/new-teams-unicode-hex-character-and-emoji/m-p/3963936
google also show up earlier similar issues...

Both flavours of Teams (traditional and "new") are affected according to my experience.

**Comment by TwiN** [comment]
To be completely honest, that seems more like an issue with Microsoft Teams than with Gatus, however, it's an issue nonetheless.

If allowing the customization of the title in the message generated by the webhook payload sent by Gatus resolves the situation, then I'd be willing to add a new `alerting.teams.title` field.

There's already a precedent for this anyways: see #602, which was made for Discord's title to be customizable.

**Comment by 221bshashank** [comment]
@TwiN sounds like a new feature. thanks

**Comment by Rodri9o** [comment]
> To be completely honest, that seems more like an issue with Microsoft Teams than with Gatus, however, it's an issue nonetheless.
> 
> If allowing the customization of the title in the message generated by the webhook payload sent by Gatus resolves the situation, then I'd be willing to add a new `alerting.teams.title` field.
> 
> There's already a precedent for this anyways: see #602, which was made for Discord's title to be customizable.

The issue is limited to the **Microsoft Teams classic** desktop client.
Gatus alert cards are rendered correctly on my phone Teams App and on the web client via Office 365.
