### ISSUE TITLE
Add Gotify provider

### ISSUE THREAD

**Issue by bugrakocabay** [TwiN/gatus#603]
### Describe the feature request

Hi @TwiN ,

[Gotify](https://github.com/gotify/server) is an open-source messaging tool, which I use for personal projects. I think having this as a provider would be useful.

### Why do you personally want this feature to be implemented?

Gotify is suitable for alerting.

### How long have you been using this project?

1 month

### Additional information

I can implement this feature if it is approved.

**Comment by TwiN** [comment]
Sounds good to me! I've been wanting to add support for Gotify as well, but just haven't found the time to.
