### ISSUE TITLE
How to install with `go install`

### ISSUE THREAD

**Issue by lpil** [TwiN/gatus#612]
### Describe the bug

Hello there! Thank you for this software.

We're not using containers so I've been trying to build this project from source. Normally I can run (for example) `go install github.com/TwiN/gatus@latest`, but when I try that with this project I get an error.

What is the appropriate command to build this program with `go install`?

Thank you
Louis

### What do you see?
This error:
```
go: github.com/TwiN/gatus@latest (in github.com/TwiN/gatus@v1.12.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

### What do you expect to see?

The project compiles.

### List the steps that must be taken to reproduce this issue

Run `go install github.com/TwiN/gatus@latest`

### Version

go version go1.21.3 linux/arm64

**Comment by bugrakocabay** [comment]
Hi @lpil 

Your command is missing version suffix `/v5`, which means semantic import versioning. Try adding it to your command and you should be good.

`go install github.com/TwiN/gatus/v5@latest`

**Comment by lpil** [comment]
Wonderful, thank you. It would be fab if this was in the documentation for folks like me who would struggle otherwise!

**Comment by TwiN** [comment]
@lpil if you'd like, you can create a PR that adds this information in a new section at the bottom of the [README's FAQ section](https://github.com/TwiN/gatus#faq).

If you've asked yourself this question, odds are, there are other people with the same question :)

**Comment by lpil** [comment]
I'm sorry, I don't feel qualified writing documentation for this project.
