### ISSUE TITLE
Ability to serve UI behind a proxy on a path 

### ISSUE THREAD

**Issue by lpil** [TwiN/gatus#613]
### Describe the feature request

Hello!

We wish to run the Gatus UI on an address like `https://internal.example.com/status` using a reverse proxy (i.g. nginx, caddy).

This works for the HTML, but the static files use absolute URLs staring with `/`, so rather than going to the correct proxied address of `https://internal.example.com/status/css/app.css` they go to `https://internal.example.com/stats/css/app.css`, without the `status` segment.

Would you accept a PR changing these URLs to be relative? So that the application can be served with any prefix?

Thanks,
Louis

**Comment by TwiN** [comment]
Duplicate of #88
