### ISSUE TITLE
feat: Add ability to delay startup

### ISSUE THREAD

**Issue by PurseChicken** [TwiN/gatus#619]
### Describe the feature request

I would like for there to be the ability to add a delay to the image starting up before executing /gatus.

I imagine this can be done internally based on an environment variable (e.g. GATUS_SLEEP). What might be easier is to modify the dockerfile to build from golang:alpine vs scratch. This will allow the use of sh or /bin/ash so that in Kubernetes, for example, we can overwrite the entrypoint be be something like `/bin/ash -c sleep 5 /gatus`.

### Why do you personally want this feature to be implemented?

The reason why I am looking into this is because when using a sidecar in Kubernetes (for example cloud-sql-proxy), the gatus image comes up before the sidecar does and that causes an error since the database is not available yet. A simple way to solve this is to add a configurable delay to the gatus image to give the sidecar enough time to be ready for connections.

**Comment by TwiN** [comment]
We could just add a sleep function with a configurable duration (e.g. `GATUS_DELAY_START_SECONDS`) at the top of the [main](https://github.com/TwiN/gatus/blob/807599c05e37fb9a0b83d36650086b0638c20d70/main.go#L16) function.

**Comment by PurseChicken** [comment]
> We could just add a sleep function with a configurable duration (e.g. `GATUS_DELAY_START_SECONDS`) at the top of the [main](https://github.com/TwiN/gatus/blob/807599c05e37fb9a0b83d36650086b0638c20d70/main.go#L16) function.

Sounds amazing!

**Comment by vax-r** [comment]
@TwiN @PurseChicken 
Hello, if this issue isn't taken yet, I would like to try to solve it

**Comment by TwiN** [comment]
@vax-r Feel free to give it a shot!
I'll assign the issue to you for now - feel free to let me know if you change your mind!

**Comment by vax-r** [comment]
Hello @TwiN , @PurseChicken 
I've made some small adjustment to the code to enable this function
Please take a look if you have time, Thank you!
