### ISSUE TITLE
Are the Gatus JSON APIs public?

### ISSUE THREAD

**Issue by lpil** [TwiN/gatus#622]
Hello!

I wish to generate some reports with the data from Gatus, to share with the teams responsible for the monitored endpoints. I can easily do this via the JSON API endpoints that Gatus' frontend uses, no problem there.

If the APIs are public I was planning to release the HTTP code as a package for the [Gleam](https://github.com/gleam-lang/gleam/) programming language, but I was unsure if that was the case.

Thanks,
Louis

edit: I published them anyway! https://hexdocs.pm/glatus/

**Comment by TwiN** [comment]
So long as you didn't explicitly add authn (see https://github.com/TwiN/gatus#security), yes.

**Comment by lpil** [comment]
Thank you
