### ISSUE TITLE
Local Development Setup

### ISSUE THREAD

**Issue by 221bshashank** [TwiN/gatus#628]
Hey guys, this may sound stupid but can anyone help me to setup this project locally so that I can try out few things...?

**Comment by TwiN** [comment]
If you want to run it locally to try out different configurations, see https://github.com/TwiN/gatus#deployment

If you want to run it locally to make changes to the code, then you have to install Go in your local environment.

**Comment by 221bshashank** [comment]
Ok thanks

**Comment by 221bshashank** [comment]
Can any one in this forum help me to implement a notification banner in UI which will show all the failed status endpoints...

**Comment by TwiN** [comment]
Please create a new issue, this is unrelated to the original issue.
