### ISSUE TITLE
TCP for database

### ISSUE THREAD

**Issue by dimacros** [TwiN/gatus#632]
### Describe the feature request

In the tcp section it says: "This works for applications such as databases", but when I try to make a connection with: "mysql://root:pass@hostname:3306/db", the typical format. It shows errors, so can you give an example to do this? Thank you

![image](https://github.com/TwiN/gatus/assets/31266588/b43dc3ed-3417-456b-86c8-6052a93cf433)

### Why do you personally want this feature to be implemented?

It help to monitoring all about my app

### How long have you been using this project?

1 month

**Comment by salim-b** [comment]
> when I try to make a connection with: "mysql://root:pass@hostname:3306/db"

You must specify the `tcp://` instead of the `mysql://` scheme, i.e.:

```
tcp://root:pass@hostname:3306/db
```

**Comment by TwiN** [comment]
@salim-b Honestly, I didn't even know that worked 😆
