### ISSUE TITLE
Request Header Fields Too Large 431

### ISSUE THREAD

**Issue by arturkasperek** [TwiN/gatus#636]
### Describe the bug

I have very large `Cookie` header send in request and as a result I get `431` errora 

### What do you see?

Request Header Fields Too Large

### What do you expect to see?

App should work

### List the steps that must be taken to reproduce this issue

1. Set very large header that has 3.5k bytes
2. Notice the 431 error

### Version

v5.7.0

**Comment by lefes** [comment]
Second on this!
Waiting for fix, cuz have the problem with keycloak auth cookies on gatus application
