### ISSUE TITLE
Raising an alert everytime a check fails

### ISSUE THREAD

**Issue by gat786** [TwiN/gatus#640]
### Describe the feature request

Currently I See that there is an option to trigger alert after a threshold has been breached but I want an alert to trigger everytime a check fails. I am failing to see how I can build something like that. 

Raising a request because I think this feature does not exist. Please let me know if exists and how I can use it.

Thanks for project, its a great tool! 👋 

### How long have you been using this project?

1 month

**Comment by tarocjsu** [comment]
No sense for this request.

**Comment by gat786** [comment]
I feel like it doesn't make any sense now that I that I think about it again.

**Comment by TwiN** [comment]
No, no, your request does make sense.
It was already requested in #379

**Comment by gat786** [comment]
Agreed the one mentioned would also solve my need.
