### ISSUE TITLE
Default dark mode

### ISSUE THREAD

**Issue by potrudeau** [TwiN/gatus#648]
### Describe the feature request

It would be nice to be able to have the dark mode activated by default ?
Someting like:
`ui.darkmode = true`

Thanks! :)

**Comment by hale177** [comment]
i like dark theme !!!   Couldn't be better as default option

**Comment by TwiN** [comment]
This change was made 3 years ago https://github.com/TwiN/gatus/commit/4ab5724fc16e3d42c5a8360fd5a9872150136a15#diff-c37cd5e977ef60f10519116a6be209492ae686c52088d4911e812880ac82bfacR75

**Comment by OscarCy** [comment]
Is this feature actually exists? I couldn't find anything related to that. Whats the structure to set dark mode on config.yaml?

**Comment by TwiN** [comment]
@OscarCy it already defaults to dark mode, but the browser remembers the last mode you set it to (afaik Gatus uses localstorage for this), so if you set it to light mode before, it would use light mode on your browser.
