### ISSUE TITLE
Push-based monitoring

### ISSUE THREAD

**Issue by r3mi** [TwiN/gatus#673]
### Describe the feature request

First, thanks for gatus, a very useful tool!
Is it possible to add push-based monitoring, where external services can report to gatus that they are up ? 
Example of such feature are [uptime-kuma](https://github.com/louislam/uptime-kuma) push, and [healthchecks.io](https://github.com/healthchecks/healthchecks). 

It could be : services would call an exposed gatus URL (with a specific `<id>` set in the config file) which would record the time of last access. Then the periodic monitoring function would set the monitoring "unhealthy"  if the heartbeat was missed in the last interval.

### Why do you personally want this feature to be implemented?

This will allow for monitoring the absence of events, eg use at the end of a periodic backup script, to be be able to monitor that the backup has not happened.

### How long have you been using this project?

3 months

### Additional information

I looked at #229 : the title "Expose an API for external applications to push statuses" seems to be similar to the above request, but the description is about something else (API to add/modify/delete endpoints).

**Comment by xsteadfastx** [comment]
thats exactly what i am missing too

**Comment by TwiN** [comment]
Superseded by #722 

Your request has been heard. I also have been wanting this feature for a long time, I've just been burning out unbeknownst to me, for too long.
