### ISSUE TITLE
Alerts triggered status is not persistent

### ISSUE THREAD

**Issue by macmoritz** [TwiN/gatus#679]
### Describe the bug

The `triggered` status of a monitor is only momentary. After a restart of gatus the information is gone.  
   
Such restarts are daily business in cloud environments. 

### What do you expect to see?

Gatus should only send one alert for a failing monitor. 

### List the steps that must be taken to reproduce this issue

1. gatus starts
2. after some time a monitored service fails
3. gatus sends an alert after checking if alert was sended before
4. gatus will not send more notifications for this monitor, which is correct (log: `[watchdog][handleAlertsToTrigger] Sending matrix alert because alert for endpoint=my-endpoint='' has been TRIGGERED`)
5. gatus restarts
6. gatus will send an alert for the monitor again

### Additional information

Fix could be to use the events from the database for checking if an alert was already sended.

**Comment by TwiN** [comment]
Yes, you're right. It's also something I've been wanting to take care of for a while.

**Comment by ser** [comment]
I would also add something like UUID of the sent alert and keep the same UUID when the alert gets resolved or sending is repeated by any reason.

**Comment by TwiN** [comment]
PR is up @ #764 but further testing is necessary
