### ISSUE TITLE
How many endpoint-defaults setting can be set ? only one setting ?

### ISSUE THREAD

**Issue by tarocjsu** [TwiN/gatus#700]
### Describe the feature request

I had been use one endpoint-defaults for default endpoints setting, but look like just can use one endpoint-defaults setting ? has any chance to use more than one endpoint-defaults settings ? Thanks.

endpoint-defaults: &defaults
  group: core
  interval: 30s
  client:
    timeout: 10s
  conditions:
    - "[STATUS] == 200"
    - "[CERTIFICATE_EXPIRATION] > 48h"
  alerts:
    - type: discord
      failure-threshold: 5
    - type: discord
      failure-threshold: 10
    - type: discord
      failure-threshold: 15
    - type: telegram
      failure-threshold: 5
    - type: telegram
      failure-threshold: 10
    - type: telegram
      failure-threshold: 15
    - type: email
      failure-threshold: 5
    - type: email
      failure-threshold: 10
    - type: email
      failure-threshold: 15

endpoints:
  - name: npm
    <<: *defaults
    url: "https://npm.xxxx.eu.org/"

### Why do you personally want this feature to be implemented?

More flexable for config.yaml setting.

**Comment by TwiN** [comment]
You can use as many as you want, you just have to name them differently.

e.g. 
```yaml
default-graphql-endpoint: &default-graphql-endpoint
```

I suggest you look up "yaml anchors"
