### ISSUE TITLE
Docker DNS server - Server misbehaving

### ISSUE THREAD

**Issue by tnesztler** [TwiN/gatus#705]
### Describe the bug

Gatus reports **random** failed health checks due to errors with Docker's internal DNS server: `server misbehaving`.

The service in question is accessible and OK. When running `dig` **from another container** pointed at this dns, I get a valid domain name resolution.

```sh
dig @127.0.0.11 subdomain.domain.tld

; <<>> DiG 9.18.24 <<>> @127.0.0.11 subdomain.domain.tld
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14720
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1432
;; QUESTION SECTION:
;subdomain.domain.tld.		IN	A

;; ANSWER SECTION:
subdomain.domain.tld.	3761	IN	CNAME	cname.tld.
cname.tld.	52	IN	A	X.X.X.X

;; Query time: 1 msec
;; SERVER: 127.0.0.11#53(127.0.0.11) (UDP)
;; WHEN: Fri Mar 15 16:30:43 CET 2024
;; MSG SIZE  rcvd: 102
```

Note: The domain names and IPs have been redacted.

### What do you see?

The UI reports an error as followed:
```sh
Get "https://subdomain.domain.tld/health-check" dial tcp: lookup subdomain.domain.tld on 127.0.0.11:53: server misbehaving
```

Note: the domain name and path have been redacted.

I tried to setup dig inside the Gatus container itself but the docker image is based on `scratch`.

### What do you expect to see?

I expect to see only errors related to the service, not Docker's internal domain name resolution.

### List the steps that must be taken to reproduce this issue

The bug is not reproducible as it is random. However, here is the basic configuration.

1. Setup an HTTP/API check set to run every 60s
2. Run the application with 120s delay
3. At random times, the health check will failed due to a "server misbehaving" error with Docker's DNS

### Version

5.7

### Additional information

How can we troubleshoot this issue i.e. a problem with Docker or Gatus itself?

**Comment by TwiN** [comment]
@tnesztler what happened? Did you manage to fix it? If so, how did you fix it?

I'm just asking in case somebody comes across the same problem in the future :)

**Comment by tnesztler** [comment]
@TwiN I reworked my entire DNS setup (I was using a DynDNS service). With the numerous calls (every minute), it was causing a lot of issues (CNAME -> CNAME (DynDNS) -> A). My public IP is changing once every few months so I manually change an A record that I own and that solved it.
Now Gatus is working as it should.
