### ISSUE TITLE
Gatus crashes when json inquiry returns null value

### ISSUE THREAD

**Issue by mikeriley** [TwiN/gatus#718]
### Describe the bug

Gatus crashes when attempting to parse a defined JSON element that returns an unexpected null value. (Ex: [BODY].health == OK is expected, but if the health routine returns a 'null' value, then Gatus crashes per the panic listing below.

### What do you see?

gatus-1  | panic: interface conversion: interface {} is nil, not map[string]interface {}
gatus-1  |
gatus-1  | goroutine 30 [running]:
gatus-1  | github.com/TwiN/gatus/v5/jsonpath.extractValue({0xc0000ec607, 0x8}, {0x0, 0x0})
gatus-1  |      /app/jsonpath/jsonpath.go:123 +0x11b
gatus-1  | github.com/TwiN/gatus/v5/jsonpath.walk({0xc0000ec607, 0x8}, {0x0, 0x0})
gatus-1  |      /app/jsonpath/jsonpath.go:43 +0x332
gatus-1  | github.com/TwiN/gatus/v5/jsonpath.Eval({0xc0000ec607, 0x8}, {0xc000560600, 0x4, 0x200})
gatus-1  |      /app/jsonpath/jsonpath.go:20 +0xc7
gatus-1  | github.com/TwiN/gatus/v5/core.sanitizeAndResolve({0xc00064f380, 0x2, 0x1316cf4?}, 0xc0003f6000)
gatus-1  |      /app/core/condition.go:277 +0x70c
gatus-1  | github.com/TwiN/gatus/v5/core.Condition.evaluate({0xc0000ec600, 0x15}, 0xc0003f6000, 0x0)
gatus-1  |      /app/core/condition.go:113 +0x92
gatus-1  | github.com/TwiN/gatus/v5/core.(*Endpoint).EvaluateHealth(0xc0005dd040)
gatus-1  |      /app/core/endpoint.go:312 +0x26a
gatus-1  | github.com/TwiN/gatus/v5/watchdog.execute(0xc0005dd040, 0xc00001cdc0, 0xc000199680, 0xe403fb?, 0x70?, 0x0, 0x0)
gatus-1  |      /app/watchdog/watchdog.go:70 +0x275
gatus-1  | github.com/TwiN/gatus/v5/watchdog.monitor(0xc0005dd040, 0xc00001cdc0, 0xc000199680, 0x0, 0x0, 0x0, 0x0, {0x18a1ea0, 0xc000110aa0})
gatus-1  |      /app/watchdog/watchdog.go:42 +0x67
gatus-1  | created by github.com/TwiN/gatus/v5/watchdog.Monitor in goroutine 1
gatus-1  |      /app/watchdog/watchdog.go:34 +0x225
gatus-1 exited with code 0

### What do you expect to see?

Gatus should gracefully handle null conditions by reporting the server did not return the expected response, and should not crash the program.

### List the steps that must be taken to reproduce this issue

1. Launch the program.
2. Define an expected JSON endpoint value (ex: [BODY].health == OK).
3. Have that particular endpoint fail with a null value response for the .health assignment.
4. Watch the fireworks.

### Version

5.8.0

### Additional information

Keep up the good work on the application. Thanks.

**Comment by TwiN** [comment]
@mikeriley Good catch!
