### ISSUE TITLE
Implement endpoints whose results are pushed into Gatus externally

### ISSUE THREAD

**Issue by TwiN** [TwiN/gatus#722]
### Describe the feature request

This feature has been requested dozens of times to me, and I'm feeling motivated to implement it right now, so here goes nothing.

The crux of it is, let's say Gatus doesn't support something, but you want to use Gatus to display and alert on that "unsupported something" anyways. Well, this is the feature that enables it.

The steps involved are:
1. Figure out a way to classify an endpoint as "external"
  1.1. said endpoint must have an individually configurable "token" which is used for authentication purposes. 
2. Create an API that allows an HTTP request to "report" a result about an endpoint
3. Said endpoint must automatically check if an alert has been triggered

### How long have you been using this project?

Forever

**Comment by r3mi** [comment]
that's great.
For step 3. , will it also include the negative "Said endpoint must automatically check if an alert has **_not_** been triggered" i.e. raise an alert if no result received within a specified period ? 
(aka push-based monitoring)

**Comment by TwiN** [comment]
@r3mi For the first implementation, probably not, but once the foundation is laid down, that'll be the next step.
