### ISSUE TITLE
fix: Add `crossorigin="use-credentials"` to the manifest.json link in index.html

### ISSUE THREAD

**Issue by rschelling** [TwiN/gatus#728]
### Describe the feature request

When using Oauth2-Proxy as forwardAuth in Traefik for gatus, the session cookie will not be sent when requesting the `manifest.json`. Therefore the `manifest.json` cannot be fetched because of missing CORS policy.

To fix this issue it would suffice to add `crossorigin="use-credentials"` to the link for the `manifest.json` in the header of the `index.html`.
Would this be possible? If necessary, i can try to create a pull request.

**Comment by TwiN** [comment]
Sure, feel free to create a PR!
