### ISSUE TITLE
Failed to insert data in storage: constraint failed: FOREIGN KEY constraint failed (787)

### ISSUE THREAD

**Issue by mani9223-oss** [TwiN/gatus#735]
### Describe the bug

We are using Gatus with SQLite DB. After it runs for a few months, Gatus throws this error. 

### What do you see?

Failed to insert data in storage: constraint failed: FOREIGN KEY constraint failed (787)

### What do you expect to see?

Gatus should run normally. In this case, I would expect the Gatus health check to fail so that it would alert the users to take necessary action.

**Comment by mani9223-oss** [comment]
@TwiN

**Comment by mani9223-oss** [comment]
As a workaround, I have recovered the old DB and put it in a new db file using sqlite command.

**Comment by TwiN** [comment]
I've never had this issue happen to me and I have had Gatus instances run for several months :S 

If I can't reproduce the issue, I don't think I can fix this
