### ISSUE TITLE
Details page is empty when CJK chars is used in endpoint name

### ISSUE THREAD

**Issue by FHU-yezi** [TwiN/gatus#749]
I use the latest version of Gatus, which is v5.10.0.

Steps to reproduce this problem:

1. create a endpoint with the name "中", which is Chinese char.
2. Start Gatus and navigate to the status page, click this endpoint item's title "中", open the details page.
3. Now you can see an empty page with only recent status shown gray dotted boxes.

The DevTools shows that the API which returns details data response with "endpoint not found".

**Comment by TwiN** [comment]
This may sound a little presumptuous, but you could just use alphanumerical characters.

I know this isn't optimal for people that want to display text in their native language, but I am personally biased toward keeping everything programming-related in English despite my native language not being French.

I'm sorry but right now, supporting multiple languages is just not something I'm willing to put any effort in. 
Perhaps if some day, I can afford to work full time on Gatus, I'll add support for different languages, but I'm still far from that.

**Comment by ichenhe** [comment]
I got an idea. How about adding a new attribute of endpoint called `display-name`? In this way, the API path still only supports English, while the UI can display any text. As far as I know, Golang has built-in utf8 support. CJK characters can be displayed without much effort.
