### ISSUE TITLE
[Question] How monitoring docker container?

### ISSUE THREAD

**Issue by EliaTolin** [TwiN/gatus#770]
Hi everyone! 

I need to monitoring a docker container. 

Contains a telegram userbot that does not expose API, how can I proceed?

**Comment by TwiN** [comment]
Not currently possible, but see existing related discussions #704 and #740

**Comment by object-Object** [comment]
I know this is an old issue, but in case anyone else comes across it trying to implement this, I was able to implement Docker container monitoring via [docker-socket-proxy](https://github.com/linuxserver/docker-socket-proxy). Configs: https://github.com/object-Object/objectobject.ca/commit/cb47bf8f0207f62f4fc5a1561b915753423a6c09

**Comment by hale177** [comment]
> I know this is an old issue, but in case anyone else comes across it trying to implement this, I was able to implement Docker container monitoring via [docker-socket-proxy](https://github.com/linuxserver/docker-socket-proxy). Configs: [object-Object/objectobject.ca@cb47bf8](https://github.com/object-Object/objectobject.ca/commit/cb47bf8f0207f62f4fc5a1561b915753423a6c09)

@object-Object  can you show a picture of your monitoring page UI  ?

**Comment by object-Object** [comment]
@hale177 Sure: https://status.objectobject.ca/endpoints/hexbug_prod-docker

<img width="1536" height="1285" alt="Image" src="https://github.com/user-attachments/assets/a44ffd0a-f805-42c1-8a43-9c1ae3912b4b" />

**Comment by hale177** [comment]
If there are multiple containers on Docker, will each one be displayed?  I see you only have one   ( **prod-docker** ).

**Comment by object-Object** [comment]
You'd have to add an endpoint to the config for each container you want to monitor. Gatus doesn't have any special support for Docker, my workaround just uses normal URL endpoints pointing at specific paths in the docker-socket-proxy URL. For example, all of the highlighted endpoints in this screenshot are for Docker containers (from https://status.objectobject.ca/):

<img width="1308" height="1050" alt="Image" src="https://github.com/user-attachments/assets/f6b35b31-93f2-49ba-b93d-8a982abfb61b" />

**Comment by hale177** [comment]
thank so much !!
