### ISSUE TITLE
Alert send to Zulip

### ISSUE THREAD

**Issue by Smiley-k** [TwiN/gatus#802]
### Describe the feature request

Receive notifications and if possible a status picture 

### Why do you personally want this feature to be implemented?

We use the internal messenger zulip and it would be handy to get notifications into it

### How long have you been using this project?

I'm just getting acquainted so I can put it into practice

### Additional information

docs https://zulip.com/api/incoming-webhooks-overview

**Comment by mehdibo** [comment]
Hello

@TwiN in the linked URL Zulip has "[Slack-compatible incoming webhook](https://zulip.com/integrations/doc/slack_incoming)"
Isn't that enough as Gatus already supports Slack?

Or should it also be implemented separately?

**Comment by TwiN** [comment]
I don't think there's anything wrong with implementing both. After all, there may be people that use both Slack and Zulip, in which case supporting both would be a bonus.
