### ISSUE TITLE
OIDC Configuration ignored

### ISSUE THREAD

**Issue by xeruf** [TwiN/gatus#817]
### Describe the bug

I have the following in my gatus configmap, deployed on kubernetes:
![image](https://github.com/TwiN/gatus/assets/13354331/ca6fe0cb-1c24-46d9-aa05-5a4bb1fa4aaa)

### What do you see?

the security configuration is ignored - nothing on the site, nothing in the logs

### What do you expect to see?

Our status page is secured as I followed https://twin.sh/articles/56/securing-gatus-with-oidc-using-auth0

### List the steps that must be taken to reproduce this issue

1. configure oidc security
2. see no change

### Version

5.7.0, updating right now

**Comment by xeruf** [comment]
whoopsie, I screwed up in the indentation :sweat_smile:

**Comment by TwiN** [comment]
@xeruf It happens to the best of us 😆
