### ISSUE TITLE
Change the Teams alert from the Office 365 connector to the Teams Workflow App Webhook Connector

### ISSUE THREAD

**Issue by westynz** [TwiN/gatus#820]
### Describe the feature request

Recently, Teams alerts in my tenant from Gatus have had the following text appended to them:

"**Action Required:** O365 connectors within Teams will be deprecated and notifications from this service will stop. [Learn more](https://aka.ms/O365ConnectorDeprecation)
about the timing and how the Workflows app provides a more flexible and secure experience. If you want to continue receiving these types of messages, you can use a workflow to post messages from a webhook request.
[Set up workflow](https://teams.microsoft.com/l/task/c3a1996d-db0f-4857-a6ea-7aabf0266b00?url=https://make.powerautomate.com/teams/store/flowCreation?templateId=d271a6f01c2545a28348d8f2cddf4c8f)"

So, reading through the first link, all Office connectors, including the Incoming Webhook connector Gatus uses are being retired in favour of the Teams Workflow App which seems to be a client for Power Automate.

There appears to be webhook connector template in the new workflow app that will operate in a similar way to the O365 webhook connector.

This (https://learn.microsoft.com/en-us/connectors/teams/?tabs=text1#microsoft-teams-webhook) page describes JSON body content required, which is in the Adaptive Card JSON format.

### Why do you personally want this feature to be implemented?

I use as Teams my main conduit for important alerts.

### How long have you been using this project?

6 months

### Additional information

I'm curious to know if other users who have configured Teams alerts are also receiving this message?

This is great project, thank you for all the hard work!

**Comment by kaleidoscopix** [comment]
+1 I just noticed the same message on all alerts to Teams today.
According to the docs, there's some fairly aggressive (IMO) timelines to this change:

> Wave 1 – effective August 15th, 2024: All new Connector creation will be blocked within all clouds
Wave 2 – effective October 1st, 2024: All connectors within all clouds will stop working

It would be fantastic to see a migration to this new method as I also use Teams as a main alerting tool for my department.

**Comment by TwiN** [comment]
Makes sense to me as well. I'm currently very busy irl, but if somebody wants to make a PR, I can have a look at it and release it.

**Comment by atc0005** [comment]
FWIW, here are some additional references that you may find useful:

- https://gist.github.com/chusiang/895f6406fbf9285c58ad0a3ace13d025
  - lots of discussion & an example script to use adaptive cards format
- https://github.com/tlolkema/simple-teams-message
  - the `action.yml` file contains an example payload that could be adapted for use here

**Comment by TwiN** [comment]
It looks like they pushed back the timeline:

> All existing connectors within all clouds will continue to work until December 2025, however using connectors beyond December 31, 2024 will require additional action.

[source](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/)
