### ISSUE TITLE
New `maintenance.timezone` config requires IANA Time Zone database

### ISSUE THREAD

**Issue by salim-b** [TwiN/gatus#848]
### Describe the bug

The [official Gatus container image](https://hub.docker.com/r/twinproduction/gatus) is missing the required timezone data to be able to properly interpret timezone values.

When e.g. setting `maintenance.timezone = "Europe/Zurich"`, Gatus panics with:

```
panic: invalid timezone specified or format not supported. Use IANA timezone format (e.g. America/Sao_Paulo): unknown time zone Europe/Zurich
```

According to the [docs of `time.LoadLocation`](https://pkg.go.dev/time#LoadLocation):

> LoadLocation looks for the IANA Time Zone database in the following locations in order:
> 
> - the directory or uncompressed zip file named by the ZONEINFO environment variable
> - on a Unix system, the system standard installation location
> - $GOROOT/lib/time/zoneinfo.zip
> - the time/tzdata package, if it was imported

A simple `apk install tzdata` fixes the panic. But importing the `time/tzdata` would also solve the issue.

### What do you see?

```
panic: invalid timezone specified or format not supported. Use IANA timezone format (e.g. America/Sao_Paulo): unknown time zone Europe/Zurich
```

### What do you expect to see?

No panic.

### List the steps that must be taken to reproduce this issue

Set `maintenance.timezone = "Europe/Zurich"`.

### Version

5.12.0

**Comment by TwiN** [comment]
I think I'd prefer going the import route if it does fix the issue

**Comment by TwiN** [comment]
@salim-b could you give it a try with the new `latest` image?

**Comment by salim-b** [comment]
@TwiN `latest` image works fine without manual `tzdata` install. 👌
