### ISSUE TITLE
Alert only on working hours

### ISSUE THREAD

**Issue by alexandrepossebom** [TwiN/gatus#874]
### Describe the feature request

It would be great to have alert configurations based on time, such as sending alerts via Telegram during working hours and via email outside of working hours.

I have services that are only used during working hours, so receiving alerts in the middle of the night is unnecessary and disruptive. Configuring alerts based on time would help me focus on what's important during off-hours.

### Why do you personally want this feature to be implemented?

Just a configuration with start time and end time in alert section.

### How long have you been using this project?

More than a year

**Comment by TwiN** [comment]
Have you checked the maintenance configuration?

**Comment by simo222** [comment]
Is it possible to configure maintenance per alert or per group?
Now i see only a global setting

**Comment by TwiN** [comment]
No, maintenance is only configurable globally right now, though it shouldn't be very difficult to also support that configuration at the endpoint level

**Comment by amai2012** [comment]
> No, maintenance is only configurable globally right now, though it shouldn't be very difficult to also support that configuration at the endpoint level

That idea seems to match https://github.com/TwiN/gatus/issues/312
