### ISSUE TITLE
[How to?] Custom Logo & icons for Frontend - Missing Documentation

### ISSUE THREAD

**Issue by Tim-orius** [TwiN/gatus#917]
### Describe the bug

Hello,
I'm upgrading from gatus v.3.7.0 to v.5.13.1 - quite a big jump in versions and so far I've used a configuration with a Dockerfile where I move my assets (img/logo.svg, favicon.png, etc. in the Dockerfile: `COPY assets ./web/static` in order to have my own logo displayed in the frontend. This worked perfectly fine in 3.7.0 but I've realised this method is deprecated by now and I've missed the new way of inserting a custom logo to the frontend. I've searched for "logo" and "icon" and found a parameter for the config.yaml defined as ui.logo but I'm missing the documentation as to what is needed to be specified there to use a local file. 
Any help / pointer to the documentation is highly appreciated.

### Version

5.13.1

**Comment by TwiN** [comment]
Hello @Tim-orius! To begin with, your way of setting the logo in the Dockerfile wasn't a feature even back then, though it is a pretty clever solution.

`ui.logo` is currently designed to work with external links, such as:
```yaml
ui:
  logo: "https://example.com/images/logo.png"
```
