### ISSUE TITLE
Receiving Client.Timeout when validating correct request

### ISSUE THREAD

**Issue by pmensik** [TwiN/gatus#934]
### Describe the bug

I have an endpoint configured which is trying to emulate the following curl command `curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' https://0g-rpc.rubynodes.io`. The curl correctly returns, however, Gatus responds with `Get "https://0g-rpc.rubynodes.io": context deadline exceeded (Client.Timeout exceeded while awaiting headers)` which I find quite confusing and unfortunately I am not able to find out what could be the issue. 
The output remains the same if I remove the `body` and `headers` parameters, adding `insecure: true` doesn't help either.
```
endpoints:
  - name: 0gChain HTTPS                 # Name of your endpoint, can be anything
    group: testnet
    url: "https://0g-rpc.rubynodes.io"
    method: POST
    body: '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}'
    headers:  
      Content-Type: application/json
    interval: 10s                  
    conditions:
      - "[CONNECTED] == true"
      - "[BODY].id == 67"
      - "[CERTIFICATE_EXPIRATION] > 48h"
```

### What do you see?

Gatus board is showing `Get "https://0g-rpc.rubynodes.io": context deadline exceeded (Client.Timeout exceeded while awaiting headers)` error while trying to validate the aforementioned endpoint above. The error can be seen on [https://status.rubynodes.io](https://status.rubynodes.io)

### What do you expect to see?

I expect to see the endpoint being correctly validated. 

### Version

latest

**Comment by TwiN** [comment]
I can replicate the issue on my end, however, interestingly enough, if you increase the client timeout like so:
```yaml
endpoints:
  - name: 0gChain HTTPS
    #...
    client:
      timeout: 5m
```
I found out that after ~1m30s, the call succeeds, and all following evaluation work normally (they take ~100ms as opposed to the first call, who takes ~1m30s):
```
2024/12/18 17:43:33 [watchdog.execute] Monitored group=testnet; endpoint=0gChain HTTPS; key=testnet_0gchain-https; success=true; errors=0; duration=1m35.291s
2024/12/18 17:43:43 [watchdog.execute] Monitored group=testnet; endpoint=0gChain HTTPS; key=testnet_0gchain-https; success=true; errors=0; duration=111ms
2024/12/18 17:43:53 [watchdog.execute] Monitored group=testnet; endpoint=0gChain HTTPS; key=testnet_0gchain-https; success=true; errors=0; duration=111ms
2024/12/18 17:44:03 [watchdog.execute] Monitored group=testnet; endpoint=0gChain HTTPS; key=testnet_0gchain-https; success=true; errors=0; duration=111ms
2024/12/18 17:44:13 [watchdog.execute] Monitored group=testnet; endpoint=0gChain HTTPS; key=testnet_0gchain-https; success=true; errors=0; duration=105ms
2024/12/18 17:44:23 [watchdog.execute] Monitored group=testnet; endpoint=0gChain HTTPS; key=testnet_0gchain-https; success=true; errors=0; duration=112ms
2024/12/18 17:44:33 [watchdog.execute] Monitored group=testnet; endpoint=0gChain HTTPS; key=testnet_0gchain-https; success=true; errors=0; duration=106ms
2024/12/18 17:44:43 [watchdog.execute] Monitored group=testnet; endpoint=0gChain HTTPS; key=testnet_0gchain-https; success=true; errors=0; duration=105ms
2024/12/18 17:44:54 [watchdog.execute] Monitored group=testnet; endpoint=0gChain HTTPS; key=testnet_0gchain-https; success=true; errors=0; duration=106ms
```
(scroll horizontally to see the duration of the call)

**Comment by pmensik** [comment]
Hmm, interesting, thanks for having a look so fast! So I suppose there's some issue with the WebSocket configuration itself on my proxy server, please feel free to close the ticket.
